### ISSUE TITLE
When clicking an agent from the empty chat window - it should show the context menu - not open the agent

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#195]

**Comment by AGasior** [comment]
@cielecki Can you provide more details? Which context menu should be visible?

**Comment by AGasior** [comment]
When user click on agent or material should see context menu it should work same as on right click

![Zrzut ekranu 2024-01-5 o 11 23 33](https://github.com/10clouds/aiconsole/assets/102804214/0ac257f5-a694-4ff1-a295-b3a0c0e54602)

**Comment by kgradzka** [comment]
Retested on Win10.

Corrected. ✔️
