### ISSUE TITLE
After closing the window using "x" on Mac - the entire app does not shut down.

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#196]
When clicking the icon it does not do anything.

**Comment by kgradzka** [comment]
I'm not able to retest this as I don't have access to device with MacOS. @jakubbilko are you able to verify it?

**Comment by jakubbilko** [comment]
@kgradzka I was the one implementing it, so I'd rather someone else check, maybe @pwksn ?

**Comment by pwksn** [comment]
I just tested this and it looks fine - when I close the last remaining aiconsole window, the entire application closes.

cc @kgradzka
