### ISSUE TITLE
400 error after adding material/agent with already existing name [ACD-667]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#201]
Migrated from issue: [ACD-667](https://10clouds.atlassian.net/browse/ACD-667) (Bug)

After clicking “Create” button for material/agent with name that's already existing 400 error is visible. User should see, for example, a popup with information that material/agent with this name is already created.,Steps to reproduce:,Payload for material:,{id: "test", name: "test", version: "0.0.1", usage: "", usage_examples: [], defined_in: "project",…}
content_api
: 
"'''\nAdd here general API description\n'''\n\ndef create():\n    '''\n    Add comment when to use this function, and add example of usage:\n    ```python\n        create()\n    ```\n    '''\n    print(\"Created\")\n\n\ndef print_list():\n    '''\n    Use this function to print 'List'.\n    Sample of use:\n    ```python\n        print_list()\n    ```\n\n    '''\n    print(\"List\")\n\n\n\ndef fibonacci(n):\n    '''\n    Use it to calculate and return the nth term of the Fibonacci sequence.\n    Sample of use:\n    ```python\n      fibonacci(10)\n    ```\n    '''\n    if n <= 0:\n        return 0\n    elif n == 1:\n        return 1\n    return fibonacci(n - 1) + fibonacci(n - 2)"
content_dynamic_text
: 
"import random\n    \nasync def content(context):\n    samples = ['sample 1' , 'sample 2', 'sample 3', 'sample 4']\n    return f'''\n# Examples of great content\n{random.sample(samples, 2)}\n\n'''.strip()"
content_static_text
: 
"content, content content\n\n## Sub header\n\nBullets in sub header:\n* Bullet 1\n* Bullet 2\n* Bullet 3"
content_type
: 
"static_text"
default_status
: 
"enabled"
defined_in
: 
"project"
id
: 
"test"
name
: 
"test"
override
: 
false
status
: 
"enabled"
type
: 
"material"
usage
: 
""
usage_examples
: 
[]
version
: 
"0.0.1" 

[ACD-667]: https://10clouds.atlassian.net/browse/ACD-667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pbaranski9411** [comment]
Backend is done.

For frontend:
- partially update of agents and materials is done from frontend by POST. It should use PATCH instead

**Comment by jakubbilko** [comment]
After rechecking:
- Toast with message appears (Material/Agent with given name already exists)
- Updates are handled with PATCH

Can we close?
