### ISSUE TITLE
Don't allow agent named 'user' [ACD-449]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#205]
Migrated from issue: [ACD-449](https://10clouds.atlassian.net/browse/ACD-449) (Sub-task)

[ACD-449]: https://10clouds.atlassian.net/browse/ACD-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
@pbaranski9411 

When I look at the code, it seems to have been implemented already in load_asset_from_fs and save_asset_to_fs, this task was supposed to have needs review label, which was added last week. was it removed when I renamed it? (I can see that you readded it?)

**Comment by cielecki** [comment]
When I think about it this probably should have been done on the validation level of the Pydantic Agent class

**Comment by cielecki** [comment]
Scratch that, we sometimes use in memory Agent instance to represent a user

**Comment by pbaranski9411** [comment]
@cielecki yes, there were no review label here :) 

Anyway, it's working ok, because backend is blocking "user" agent. But there were no proper message to the user + no proper response. So if it's something we don't want to do it's ok to close the PR. Let me know what do you think
