### ISSUE TITLE
Managing Materials and Agents through AIConsole commands (natural language)

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#206]
Migrated from issue: [ACD-459](https://10clouds.atlassian.net/browse/ACD-459) (Task)

[ACD-459]: https://10clouds.atlassian.net/browse/ACD-459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pbaranski9411** [comment]
- say: "create a note with the previous message"
- say: "create a material with previous message"
- "what are the available materials on the system?"

**Comment by pbaranski9411** [comment]
Duplicate: https://github.com/10clouds/aiconsole/issues/434
