### ISSUE TITLE
BE needed [ACD-732]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#207]
Migrated from issue: [ACD-732](https://10clouds.atlassian.net/browse/ACD-732) (Sub-task)

[ACD-732]: https://10clouds.atlassian.net/browse/ACD-732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
