### ISSUE TITLE
[Hosted] BE needed for users management

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#208]
Migrated from issue: [ACD-733](https://10clouds.atlassian.net/browse/ACD-733) (Sub-task)

[ACD-733]: https://10clouds.atlassian.net/browse/ACD-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Duplicate

**Comment by cielecki** [comment]
Silly specific task
