### ISSUE TITLE
Issue with encoding of temperature symbol [ACD-788]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#209]
Migrated from issue: [ACD-788](https://10clouds.atlassian.net/browse/ACD-788) (Bug)

After asking agent for the weather incorrect symbols appear in the analysis view. At the same time the Celsius symbol looks correct in the chat. 

[ACD-788]: https://10clouds.atlassian.net/browse/ACD-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by AGasior** [comment]
I checked it and now we have incorrect signs in analysis message

![Zrzut ekranu 2024-01-12 o 13 04 22](https://github.com/10clouds/aiconsole/assets/102804214/4bce0a35-6ba5-4f80-9cc7-0f6317d5910f)
![Zrzut ekranu 2024-01-12 o 13 04 41](https://github.com/10clouds/aiconsole/assets/102804214/eb385eec-2576-4835-b5ab-a91847bb983d)

**Comment by udislau** [comment]
The issue is on OpenAI API side.
