### ISSUE TITLE
Editors are drifting apart [ACD-804]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#210]
Migrated from issue: [ACD-804](https://10clouds.atlassian.net/browse/ACD-804) (Bug)

Editors are drifting apart, screenshot needed.

[ACD-804]: https://10clouds.atlassian.net/browse/ACD-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by AGasior** [comment]
@cielecki we don't have screenshot

**Comment by aga-gasinska** [comment]
@cielecki is it still valid? if yes, pls provide a sceenshot

**Comment by cielecki** [comment]
No idea what this was about
