### ISSUE TITLE
Warning reported by Kuba Bilko [ACD-818]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#211]
Migrated from issue: [ACD-818](https://10clouds.atlassian.net/browse/ACD-818) (Bug)

  

[ACD-818]: https://10clouds.atlassian.net/browse/ACD-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jakubbilko** [comment]
I think this might actually be related to how `ReactMarkdown` works internally, so we might not be able to fix this issue.

**Comment by jakubbilko** [comment]
Upon further investigation, this is the expected behavior as `ReactMarkdown` only allows specific protocols for links (http, https, mailto, and tel). Everything else is parsed to `javascript:void(0)`. We can pass `null` to the `transformLinkUri` to allow all urls.
