### ISSUE TITLE
Uncaught (in promise) DOMException: The user aborted a request. [ACD-845]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#212]
Migrated from issue: [ACD-845](https://10clouds.atlassian.net/browse/ACD-845) (Bug)

Steps to reproduce: 

[ACD-845]: https://10clouds.atlassian.net/browse/ACD-845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kgradzka** [comment]
Retested on the newest version on Win10. Bug no longer occurs.
