### ISSUE TITLE
Set agent avatar & execution mode  - backend integration [ACD-882]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#214]
Migrated from issue: [ACD-882](https://10clouds.atlassian.net/browse/ACD-882) (Task)

UI is ready, but we do not have a backend for that 

[ACD-882]: https://10clouds.atlassian.net/browse/ACD-882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kilodilo** [comment]
It is this Agent settings page https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=2068%3A8229&mode=design&t=xpRuq7zXGtgCdhYa-1

**Comment by pbaranski9411** [comment]
Backend is done, frontend should be done

**Comment by kgradzka** [comment]
Tested on the 0.2.10-rc.4 on Win10.

It's possible to change agent's avatar. ✔️ 
![retest_issue_214_1](https://github.com/10clouds/aiconsole/assets/61430006/aa0e52c8-c64c-4a2e-bbd5-1ab1054b21fe)
![retest_issue_214_2](https://github.com/10clouds/aiconsole/assets/61430006/f6b9b048-3b1c-49d1-92a8-52b937be3036)
