### ISSUE TITLE
Pre-release procedure [ACD-874]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#215]
Migrated from issue: [ACD-874](https://10clouds.atlassian.net/browse/ACD-874) (Task)
Steps to be checked before release of the product 

[ACD-874]: https://10clouds.atlassian.net/browse/ACD-874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by aga-gasinska** [comment]
I found the following doc related to this: https://10clouds.atlassian.net/wiki/spaces/1A/pages/3988553743/Release+procedur

**Comment by aga-gasinska** [comment]
@udislau it'll be good to also have a doc related to the release procedure (we can meet and discuss it together)

**Comment by aga-gasinska** [comment]
https://github.com/10clouds/aiconsole/wiki/Release-new-version
