### ISSUE TITLE
Countdown agent responding in a loop [ACD-859]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#216]
Migrated from issue: [ACD-859](https://10clouds.atlassian.net/browse/ACD-859) (Bug)

Steps to reproduce:,*Tested on draft version downloaded from Github. 

[ACD-859]: https://10clouds.atlassian.net/browse/ACD-859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by udislau** [comment]
Fixed and tested
