### ISSUE TITLE
Sentry issues [ACD-852]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#217]
Migrated from issue: [ACD-852](https://10clouds.atlassian.net/browse/ACD-852) (Bug)

We need to investigate the build process and why it fails to produce a working build. It works after removing Sentry which might point to an env var problem. The env vars were added to the repository secrets (`VITE_SENTRY_DSN` and `BE_SENTRY_DSN`). 

[ACD-852]: https://10clouds.atlassian.net/browse/ACD-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by khdevel** [comment]
As far as I see the `VITE_SENTRY_DSN` and `BE_SENTRY_DSN` are in the GH Actions Secrets. I remember that the values were properly created so, they should be valid. Please check if the code which handles them is fine and in case all is good I might help from the DevOps site.

**Comment by jakubbilko** [comment]
I've created a PR for the backend part (since that's where the heavy lifting is done): #545

**Comment by cielecki** [comment]
PR is accepted

**Comment by cielecki** [comment]
although I don't know how to access the analytics dashboard

**Comment by jakubbilko** [comment]
@cielecki you have been added by @khdevel to the account. You can login with your 10C gmail here: https://eu.aptabase.com/auth
