### ISSUE TITLE
Modal [ACD-833]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#218]
Migrated from issue: [ACD-833](https://10clouds.atlassian.net/browse/ACD-833) (Sub-task)

[ACD-833]: https://10clouds.atlassian.net/browse/ACD-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
