### ISSUE TITLE
Tooltip [ACD-832]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#219]
Migrated from issue: [ACD-832](https://10clouds.atlassian.net/browse/ACD-832) (Sub-task)

[ACD-832]: https://10clouds.atlassian.net/browse/ACD-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
