### ISSUE TITLE
Menu (Context menu) [ACD-831]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#220]
Migrated from issue: [ACD-831](https://10clouds.atlassian.net/browse/ACD-831) (Sub-task)

[ACD-831]: https://10clouds.atlassian.net/browse/ACD-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
