### ISSUE TITLE
Tabs [ACD-829]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#222]
Migrated from issue: [ACD-829](https://10clouds.atlassian.net/browse/ACD-829) (Sub-task)

[ACD-829]: https://10clouds.atlassian.net/browse/ACD-829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
