### ISSUE TITLE
Replace Mantine with RadixUI [ACD-828]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#223]
Migrated from issue: [ACD-828](https://10clouds.atlassian.net/browse/ACD-828) (Task)

[ACD-828]: https://10clouds.atlassian.net/browse/ACD-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kgradzka** [comment]
Regression done on Win10 as per Maciek's suggestion. ✔️
