### ISSUE TITLE
Creating 0.2.2 version [ACD-824]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#224]
Migrated from issue: [ACD-824](https://10clouds.atlassian.net/browse/ACD-824) (Task)

Topic on Slack: ,  

[ACD-824]: https://10clouds.atlassian.net/browse/ACD-824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Looks like it's no longer relevant
