### ISSUE TITLE
Design review: When posting a large message it's hard to find the send button [ACD-821]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#225]
Migrated from issue: [ACD-821](https://10clouds.atlassian.net/browse/ACD-821) (Bug)

[ACD-821]: https://10clouds.atlassian.net/browse/ACD-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
@kilodilo Was this implemented?

**Comment by kilodilo** [comment]
Yes, this looks like this now 
![image](https://github.com/10clouds/aiconsole/assets/152965457/330b39f5-447a-403b-82af-945272e8b612)
