### ISSUE TITLE
Design review: After clicking edit I have a large area which looks wierd and blends with the background [ACD-820]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#226]
Migrated from issue: [ACD-820](https://10clouds.atlassian.net/browse/ACD-820) (Bug)

[ACD-820]: https://10clouds.atlassian.net/browse/ACD-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by AGasior** [comment]
Duplicated [#226](https://github.com/10clouds/aiconsole/issues/226)

**Comment by kgradzka** [comment]
Duplicate of https://github.com/10clouds/aiconsole/issues/465.
