### ISSUE TITLE
Spell checker marks a lot of typos

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#229]
Migrated from issue: [ACD-812](https://10clouds.atlassian.net/browse/ACD-812) (Bug)

Issue reported by user via Discord: , ,  

[ACD-812]: https://10clouds.atlassian.net/browse/ACD-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jakubbilko** [comment]
Some additional info on the electron spellchecker:

https://www.electronjs.org/docs/latest/tutorial/spellchecker

```
On macOS as we use the native APIs there is no way to set the language that the spellchecker uses. 
By default on macOS the native spellchecker will automatically detect the language being used for you.
```
