### ISSUE TITLE
Errors when creating project

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#230]
Migrated from issue: [ACD-811](https://10clouds.atlassian.net/browse/ACD-811) (Bug)

User on Discord reported errors: ,  

[ACD-811]: https://10clouds.atlassian.net/browse/ACD-811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pbaranski9411** [comment]
To devops: Where to test things on windows?

**Comment by aga-gasinska** [comment]
wirtual machines with Windows will be provided

**Comment by aga-gasinska** [comment]
wirtual machines has been provided

**Comment by udislau** [comment]
Fixed
