### ISSUE TITLE
App empty screen after app loader finished the process [ACD-787]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#232]
Migrated from issue: [ACD-787](https://10clouds.atlassian.net/browse/ACD-787) (Task)

It's strange that when APP loader window finish loading we get empty screen for about 5-8secs. What are the options here? ,Can we show APP loader for longer time or can we implement lazy loading inside an app? 

[ACD-787]: https://10clouds.atlassian.net/browse/ACD-787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by aga-gasinska** [comment]
Checked it few times on MacOS and Windows and it always worked as expected.
