### ISSUE TITLE
When I interrput console by sending a message, console starts to generate 2 message conncurrently [ACD-782]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#234]
Migrated from issue: [ACD-782](https://10clouds.atlassian.net/browse/ACD-782) (Bug)

Kiedy Console coś sobie robi i są streamowane tokeny z wiadomości i się wysyła kolejną wiadomość to odpala się kolejna analiza i są dwie wiadomości pisane 

[ACD-782]: https://10clouds.atlassian.net/browse/ACD-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant - implementation changed
