### ISSUE TITLE
Agent asks about star in GH [ACD-781]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#235]
Migrated from issue: [ACD-781](https://10clouds.atlassian.net/browse/ACD-781) (Task)

The assistant agent should ask our user about star on GH.  

[ACD-781]: https://10clouds.atlassian.net/browse/ACD-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kgradzka** [comment]
Retested on the newest changes on Win10.

Changes made, works as expected. ✔️ 
![issue_235_retest](https://github.com/10clouds/aiconsole/assets/61430006/8c840d0f-08a6-43c1-b6b2-1d2db21f9c46)

**Comment by kgradzka** [comment]
Retested on the newest changes on Win10.

Changes made, works as expected. ✔️ 
![issue_235_retest](https://github.com/10clouds/aiconsole/assets/61430006/8c840d0f-08a6-43c1-b6b2-1d2db21f9c46)
