### ISSUE TITLE
Sometimes the overridde info in asset editors is out of sync with reality (don't rememeber exact scenarios) [ACD-777]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#236]
Migrated from issue: [ACD-777](https://10clouds.atlassian.net/browse/ACD-777) (Bug)

[ACD-777]: https://10clouds.atlassian.net/browse/ACD-777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pbaranski9411** [comment]
Needs to be tested and steps reproduced first (example?)

**Comment by kgradzka** [comment]
Tried to reproduce it few times but it wasn't appearing anywhere.
