### ISSUE TITLE
When there are no tokens being streamed for a while, and the request did not produce an error, show an indicator that the request is still in progress [ACD-775]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#237]
Migrated from issue: [ACD-775](https://10clouds.atlassian.net/browse/ACD-775) (Task)

[ACD-775]: https://10clouds.atlassian.net/browse/ACD-775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Blocked by #501

**Comment by aga-gasinska** [comment]
if designs needed please ping @kilodilo

**Comment by AGasior** [comment]
Frontend is ready, we need to implement logic related with `message.is_streaming` on Backend, because now we only have this value as a false

**Comment by udislau** [comment]
@AGasior plz test it.

**Comment by AGasior** [comment]
@udislau Indicator is visible before message is generating
https://github.com/10clouds/aiconsole/assets/102804214/ffdb5693-4da1-4906-9503-3e4dc1cff3e2

**Comment by cielecki** [comment]
This does not work, I'm testing it with command "is x.com or asd.pl available?" for automator

**Comment by AGasior** [comment]
@udislau message.is_streaming is always false, can you check it?

https://github.com/10clouds/aiconsole/assets/102804214/3cf92aca-7d0d-49ab-a1a4-2db543aadf6e
