### ISSUE TITLE
Review the changes by Maciej Topor and full release of full minions? [ACD-771]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#238]
Migrated from issue: [ACD-771](https://10clouds.atlassian.net/browse/ACD-771) (Task)

[ACD-771]: https://10clouds.atlassian.net/browse/ACD-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
