### ISSUE TITLE
Release Minions with GPT-4 Turbo [ACD-770]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#239]
Migrated from issue: [ACD-770](https://10clouds.atlassian.net/browse/ACD-770) (Task)

[ACD-770]: https://10clouds.atlassian.net/browse/ACD-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
