### ISSUE TITLE
Ability to run this on 3.5 (via setup)

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#242]
Migrated from issue: [ACD-767](https://10clouds.atlassian.net/browse/ACD-767) (Task)

[ACD-767]: https://10clouds.atlassian.net/browse/ACD-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by aga-gasinska** [comment]
no longer relevant
