### ISSUE TITLE
Fix needed: Unable to locally build the app on a Mac without signing credentials [ACD-758]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#244]
Migrated from issue: [ACD-758](https://10clouds.atlassian.net/browse/ACD-758) (Task)

[ACD-758]: https://10clouds.atlassian.net/browse/ACD-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Workaround for now:

Remove those from forge.config.cjs
<img width="823" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/75c5091a-bcf3-4a0f-8f5d-c9fa50bc9796">

and run yarn make

This needs to be a separate command in package.json

**Comment by cielecki** [comment]
Add a separate command

**Comment by jakubbilko** [comment]
Done, added a new command: `yarn make:local`

**Comment by aga-gasinska** [comment]
tested by @udislau and it's fine
