### ISSUE TITLE
Is it possible to not show partial commands and partial image urls when streaming tokens? [ACD-754]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#247]
Migrated from issue: [ACD-754](https://10clouds.atlassian.net/browse/ACD-754) (Task)

[ACD-754]: https://10clouds.atlassian.net/browse/ACD-754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jakubbilko** [comment]
Some additional info on the electron spellchecker:

https://www.electronjs.org/docs/latest/tutorial/spellchecker

```
On macOS as we use the native APIs there is no way to set the language that the spellchecker uses. By default on macOS the native spellchecker will automatically detect the language being used for you.
```

**Comment by aga-gasinska** [comment]
possible solution: if you have a partial link, do not render it

**Comment by jakubbilko** [comment]
Good reference found by @cielecki 
https://shopify.engineering/sidekicks-improved-streaming

**Comment by aga-gasinska** [comment]
images and links
