### ISSUE TITLE
Custom execution modes can now send multiple messages [ACD-752]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#248]
Migrated from issue: [ACD-752](https://10clouds.atlassian.net/browse/ACD-752) (Task)

[ACD-752]: https://10clouds.atlassian.net/browse/ACD-752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
