### ISSUE TITLE
More convinient way to deploy [ACD-751]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#249]
Migrated from issue: [ACD-751](https://10clouds.atlassian.net/browse/ACD-751) (Task)

Right now in order to create a new version:,* I have to bump the version in ./electron/package.json,* run propagate_version from ./electron directory,* commit and push,* run workflow manually,* monitor the workflow for errors,* go to releases, click the release, set as not-pre release and as latest, click publish,ALSO EDIT RELEASE NOTES 

[ACD-751]: https://10clouds.atlassian.net/browse/ACD-751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by khdevel** [comment]
For now the Release can be done according to below steps:
1. Push the `tag` to mark the commit you want to release -> the **pre-release** will be created
2. Test the **pre-release** artefacts
3. If all is fine, manually create the **Release** from the **pre-release**

**Comment by khdevel** [comment]
Currently the `python-publish.yml` is being modified and setup to work when the final release is created.

**Comment by cielecki** [comment]
@udislau Is this good enough?
