### ISSUE TITLE
How to organize directory sharing between multiple computers? [ACD-744]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#253]
Migrated from issue: [ACD-744](https://10clouds.atlassian.net/browse/ACD-744) (Task)

[ACD-744]: https://10clouds.atlassian.net/browse/ACD-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Somewhat related to: #243 , maybe a duplicate?

**Comment by cielecki** [comment]
Duplicate of #243
