### ISSUE TITLE
Version 0.2.1-alpha27 The release did not switch the directory to ./chats wtf? [ACD-743]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#254]
Migrated from issue: [ACD-743](https://10clouds.atlassian.net/browse/ACD-743) (Bug)

Nie ma tego fixa: ,  mimo ze ma taga odpowiedniego 

[ACD-743]: https://10clouds.atlassian.net/browse/ACD-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
