### ISSUE TITLE
Forcing agents stopped working [ACD-742]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#255]
Migrated from issue: [ACD-742](https://10clouds.atlassian.net/browse/ACD-742) (Bug)

[ACD-742]: https://10clouds.atlassian.net/browse/ACD-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
