### ISSUE TITLE
VEnv creation takes too long? A user friendly solution to this problem. [ACD-741]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#256]
Migrated from issue: [ACD-741](https://10clouds.atlassian.net/browse/ACD-741) (Bug)

[ACD-741]: https://10clouds.atlassian.net/browse/ACD-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Still relevant

**Comment by cielecki** [comment]
Related to #377

**Comment by udislau** [comment]
Duplicate #460
