### ISSUE TITLE
In agents "system" should be optional and there should be an ability to have extra parameters read from agent file (execution modes)

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#257]
Migrated from issue: [ACD-740](https://10clouds.atlassian.net/browse/ACD-740) (Task)

[ACD-740]: https://10clouds.atlassian.net/browse/ACD-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pbaranski9411** [comment]
@cielecki I will need more details here, what should be done? 🤔

**Comment by pbaranski9411** [comment]
From frontend I should be able to change every parameters for execution modes

**Comment by pbaranski9411** [comment]
Related to: https://github.com/10clouds/aiconsole/issues/325

**Comment by cielecki** [comment]
Duplicate of #858
