### ISSUE TITLE
Project loading screen [ACD-734]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#258]
Migrated from issue: [ACD-734](https://10clouds.atlassian.net/browse/ACD-734) (Task)

Hey, we should add a loading screen for project opening because right now it takes some time to open it and it is awkward without anything showed.,The design: https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=1837%3A12169&mode=design&t=41o7wjJ58hvzkQVx-1

[ACD-734]: https://10clouds.atlassian.net/browse/ACD-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kilodilo** [comment]
This task is done, projects load quite fast and the setting icon rotating is good enoguh

**Comment by kilodilo** [comment]
This task is done :) We only changed the loading icon to the new one
![Ellipsis-1 9s-64px](https://github.com/10clouds/aiconsole/assets/152965457/4b173f0c-fffd-49ba-97dc-ea82fd6d189a)
