### ISSUE TITLE
Some backend CI tests [ACD-723]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#261]
Migrated from issue: [ACD-723](https://10clouds.atlassian.net/browse/ACD-723) (Task)

[ACD-723]: https://10clouds.atlassian.net/browse/ACD-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pbaranski9411** [comment]
@cielecki where we are going to run those tests? I think we need a separate "server" or "place" where we will run it, because some of the features are going to generate files, which we don't want to store on production, so python-publish step might be not good place to do that

**Comment by pbaranski9411** [comment]
Tests should be run on every PR and main
