### ISSUE TITLE
Add Table format in chat [ACD-721]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#262]
Migrated from issue: [ACD-721](https://10clouds.atlassian.net/browse/ACD-721) (Task)

Hey, we should add table formatting to our chat. Here is my solution:, ,with option to sort by column,and option to download as xml (the most common format I think),What do you think about that? 

[ACD-721]: https://10clouds.atlassian.net/browse/ACD-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Duplicate of #213
