### ISSUE TITLE
Convert !xxx notation from py notebook files to python execution [ACD-719]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#263]
Migrated from issue: [ACD-719](https://10clouds.atlassian.net/browse/ACD-719) (Task)

It works for single line code right now, but not when injected in the code somewhere else.,do Py notebooks support “!” notation on any line? 

[ACD-719]: https://10clouds.atlassian.net/browse/ACD-719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Has this been done or not?

**Comment by cielecki** [comment]
This has already been implemented

**Comment by aga-gasinska** [comment]
@cielecki your comment is needed here

**Comment by cielecki** [comment]
When AIConsole needs to run a shell command it prefixes it with "!", this should properly be generated and executed.
