### ISSUE TITLE
Refactor switch statements [ACD-663]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#269]
Migrated from issue: [ACD-663](https://10clouds.atlassian.net/browse/ACD-663) (Task)

https://github.com/10clouds/aiconsole/pull/110#discussion_r1400685326, and also ,https://github.com/10clouds/aiconsole/pull/110#discussion_r1400693879 

[ACD-663]: https://10clouds.atlassian.net/browse/ACD-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
