### ISSUE TITLE
aiconsole.ai - issue with cache validation [ACD-659]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#270]
Migrated from issue: [ACD-659](https://10clouds.atlassian.net/browse/ACD-659) (Task)

In some cases when someone wants to move to the AIC Discord from the landing page, Discord shows that the link is not active. There might be some issue with cache validation on the landing.

[ACD-659]: https://10clouds.atlassian.net/browse/ACD-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Is this still an issue?

**Comment by AGasior** [comment]
Buttons "discord" navigate to https://discord.gg/gYPJqFC7hF

**Comment by kgradzka** [comment]
Retested on newest versions of Chrome, Firefox and Edge. Discord button redirects directly to the discord. ✔️
