### ISSUE TITLE
Design review: Back button when editing material or agent [ACD-614]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#272]
Migrated from issue: [ACD-614](https://10clouds.atlassian.net/browse/ACD-614) (Task)

When the user wants to edit/open material and/or an agent they are taken to agent/material window. However, If the user needs to go back to the chat they may not be able to find the chat they were working on. A “Back to chat” button should take the user to the chat and specific place in the chat they finished working.,CC: , , ,  

[ACD-614]: https://10clouds.atlassian.net/browse/ACD-614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
@kilodilo Can you verify the status of this?

**Comment by kilodilo** [comment]
Back button should be implemented in the newest release I suppose - together with new view of material and agent editor.
Maciej Topor worked on that and it should be done.

**Comment by kilodilo** [comment]
This was implemented. I'm closing the issue
