### ISSUE TITLE
Do not wrap lines in the text editor when editing code in materials [ACD-609]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#273]
Migrated from issue: [ACD-609](https://10clouds.atlassian.net/browse/ACD-609) (Task)

[ACD-609]: https://10clouds.atlassian.net/browse/ACD-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by AGasior** [comment]
We have it already fixed

<img width="1033" alt="Zrzut ekranu 2024-01-12 o 09 01 34" src="https://github.com/10clouds/aiconsole/assets/102804214/ac8a26bc-5c7c-4f94-a281-6ead502262b2">
