### ISSUE TITLE
App tracking [ACD-589]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#275]
Migrated from issue: [ACD-589](https://10clouds.atlassian.net/browse/ACD-589) (Task)

 Let’s discuss after your holiday.,CC: , ,  

[ACD-589]: https://10clouds.atlassian.net/browse/ACD-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
There are no commits / documentation attached for review.

**Comment by kgradzka** [comment]
@jakubbilko is there anything to test yet? I'm seeing Maciej's comment and that this was assigned to you again but "QA" label is still visible 🤔
