### ISSUE TITLE
The automator is having trouble with tasks [ACD-536]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#284]
Migrated from issue: [ACD-536](https://10clouds.atlassian.net/browse/ACD-536) (Task)

[ACD-536]: https://10clouds.atlassian.net/browse/ACD-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
This should work now

**Comment by aga-gasinska** [comment]
Checked it and didn't see any issues with automator
