### ISSUE TITLE
Research app stores where we can submit the application, Mac App Store, anywhere else? [ACD-534]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#285]
Migrated from issue: [ACD-534](https://10clouds.atlassian.net/browse/ACD-534) (Task)

[ACD-534]: https://10clouds.atlassian.net/browse/ACD-534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by aga-gasinska** [comment]
@cielecki I leave it for you to review it

**Comment by aga-gasinska** [comment]
I'm closing this one as we have separate issues related to the releases on each of these stores
https://github.com/10clouds/aiconsole/issues/293
https://github.com/10clouds/aiconsole/issues/706
https://github.com/10clouds/aiconsole/issues/705
https://github.com/10clouds/aiconsole/issues/292

**Comment by aga-gasinska** [comment]
Maybe it's worth considering as well https://theresanaiforthat.com/
