### ISSUE TITLE
Proposal for auto-triggering AIConsole release (to pip and rebuild everything) to be developer-friendly [ACD-533]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#286]
Migrated from issue: [ACD-533](https://10clouds.atlassian.net/browse/ACD-533) (Task)

[ACD-533]: https://10clouds.atlassian.net/browse/ACD-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by khdevel** [comment]
I think it is covered by the [249](https://github.com/10clouds/aiconsole/issues/249). For now leave it as it is and test the release process. In case of some problems or upgrades we will proceed.
