### ISSUE TITLE
Editing the user's Avatar and username [ACD-531]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#287]
Migrated from issue: [ACD-531](https://10clouds.atlassian.net/browse/ACD-531) (Task)

While doing Agent avatar.

[ACD-531]: https://10clouds.atlassian.net/browse/ACD-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by udislau** [comment]
Duplicate, https://github.com/10clouds/aiconsole/issues/349
