### ISSUE TITLE
We need to determine the size in which the desktop console starts, as there is currently a scrollbar and the top is cut off [ACD-502]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#296]
Migrated from issue: [ACD-502](https://10clouds.atlassian.net/browse/ACD-502) (Task)

[ACD-502]: https://10clouds.atlassian.net/browse/ACD-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jakubbilko** [comment]
@kgradzka pls verify whether the window position/size gets remembered correctly.

**Comment by kgradzka** [comment]
Tested on: 0.2.10-rc.1

Window size is remembered correctly after closing and then opening AIConsole, even if there is more than one window opened. ✔️
