### ISSUE TITLE
Editing agent and materials before sending the message? Does it make sense? Is it needed? [ACD-501]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#297]
Migrated from issue: [ACD-501](https://10clouds.atlassian.net/browse/ACD-501) (Task)

Bartek mentioned that he would like to have per chat setup of choosen  (forced) agent 

[ACD-501]: https://10clouds.atlassian.net/browse/ACD-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Duplicate
