### ISSUE TITLE
Recent projects should show the number of materials, agents, etc. per project [ACD-486]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#299]
Migrated from issue: [ACD-486](https://10clouds.atlassian.net/browse/ACD-486) (Task)

We agreed on showing only custom materials number there. I suggest showing it like this:,  

[ACD-486]: https://10clouds.atlassian.net/browse/ACD-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
This frontend is ready from what I understand

**Comment by pbaranski9411** [comment]
DUPLICATED. Closing this, will be done here: https://github.com/10clouds/aiconsole/issues/378
