### ISSUE TITLE
Confirmation modal redesign [ACD-445]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#301]
Migrated from issue: [ACD-445](https://10clouds.atlassian.net/browse/ACD-445) (Task)

figma: ,link 

[ACD-445]: https://10clouds.atlassian.net/browse/ACD-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
@kilodilo Can you check what is the status of those?

**Comment by aga-gasinska** [comment]
@kilodilo is this task still valid?

**Comment by kilodilo** [comment]
no, let's leave it for now. we can close this issue.
