### ISSUE TITLE
Infrastructure for versioning messages and materials [ACD-424]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#302]
Migrated from issue: [ACD-424](https://10clouds.atlassian.net/browse/ACD-424) (Task)

potrzebny:,Powiązane z: ,  

[ACD-424]: https://10clouds.atlassian.net/browse/ACD-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Duplicate of #289
