### ISSUE TITLE
Przechowywanie credentiali [ACD-423] (translated)

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#303]
Migrated from issue: [ACD-423](https://10clouds.atlassian.net/browse/ACD-423) (Task)

Jak trzymamy na backendzie klucze openAI? W plaintext? w .aic? w settings.toml? 

[ACD-423]: https://10clouds.atlassian.net/browse/ACD-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Duplicate
