### ISSUE TITLE
Proper tutorial agent and materials about AIConsole [ACD-420]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#305]
Migrated from issue: [ACD-420](https://10clouds.atlassian.net/browse/ACD-420) (Task)

Also make sure that there are no halucinations for questions on the welcome screen 

[ACD-420]: https://10clouds.atlassian.net/browse/ACD-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Duplicate of #304
