### ISSUE TITLE
Zmigrowanie lub napisanie API [ACD-385] (translated)

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#313]
Migrated from issue: [ACD-385](https://10clouds.atlassian.net/browse/ACD-385) (Sub-task)

odwzorowanie api dla agents na podstawie materiałów 

[ACD-385]: https://10clouds.atlassian.net/browse/ACD-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
