### ISSUE TITLE
Material form validation. [ACD-366]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#316]
Migrated from issue: [ACD-366](https://10clouds.atlassian.net/browse/ACD-366) (Task)

[ACD-366]: https://10clouds.atlassian.net/browse/ACD-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
This is already done.
