### ISSUE TITLE
Review: adjusting the end point request types to rest API [ACD-365]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#317]
Migrated from issue: [ACD-365](https://10clouds.atlassian.net/browse/ACD-365) (Task)

[ACD-365]: https://10clouds.atlassian.net/browse/ACD-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Verify if POST/PATCH/DELETE etc are properly used
