### ISSUE TITLE
Information texts 'what to enter here' in the materials editor. [ACD-337]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#320]
Migrated from issue: [ACD-337](https://10clouds.atlassian.net/browse/ACD-337) (Task)

[ACD-337]: https://10clouds.atlassian.net/browse/ACD-337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kilodilo** [comment]
It is  old task and not relevant anymore, new material editor has those descriptions
