### ISSUE TITLE
[Research required] Build / Find a test framework for processing chat to monitor issues like looping agents [ACD-329]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#322]
Migrated from issue: [ACD-329](https://10clouds.atlassian.net/browse/ACD-329) (Task)

[ACD-329]: https://10clouds.atlassian.net/browse/ACD-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Important aspects: smart caching (probably in files?)

**Comment by cielecki** [comment]
Similar implementation in Typescript: https://github.com/10clouds/10minions-engine/blob/main/score/runScore.ts

**Comment by pbaranski9411** [comment]
Have framework + test + % if it's done correctly.
For now, it could be only on local (no CI/CD)

**Comment by cielecki** [comment]
How to run it?

**Comment by cielecki** [comment]
Please put this in wiki/readme

**Comment by pbaranski9411** [comment]
@cielecki done. I assigned it to you, so you can test it and close if it's ok for you

**Comment by aga-gasinska** [comment]
reviewed by @cielecki and if fine closed
