### ISSUE TITLE
Abiltiy to set custom execution modes by the user in agents (specify a module?) [ACD-300]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#325]
Migrated from issue: [ACD-300](https://10clouds.atlassian.net/browse/ACD-300) (Task)

[ACD-300]: https://10clouds.atlassian.net/browse/ACD-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Rework this so, it's possible to specify a full module

**Comment by cielecki** [comment]
This is almost implemented, you can specify a module - but the accept path is not implemeneted

**Comment by pbaranski9411** [comment]
Check accepting code for that (we can use example from repository to test it out)

**Comment by pbaranski9411** [comment]
Related task: https://github.com/10clouds/aiconsole/issues/358
