### ISSUE TITLE
[Audyt] Check errors in python before saving in materials editor [ACD-298]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#326]
Migrated from issue: [ACD-298](https://10clouds.atlassian.net/browse/ACD-298) (Task)

Errors to Audit, Syntax Highlighting for Python Code

[ACD-298]: https://10clouds.atlassian.net/browse/ACD-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
This was assigned to Kinga for review.

**Comment by cielecki** [comment]
Probably no longer relevant
