### ISSUE TITLE
Replication of backend data structures, handling and file format for Agents to mimic Materials [ACD-288]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#327]
Migrated from issue: [ACD-288](https://10clouds.atlassian.net/browse/ACD-288) (Task)

Migracja agentów na tomle. Trzeba przejrzeć czym się różni kod materiałów od agentów i to przemigrować, może wyciągnąć wspólną funkcjonalność do “utilków”. ,Tylko jeden agent może być forced.  

[ACD-288]: https://10clouds.atlassian.net/browse/ACD-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
This was done already
