### ISSUE TITLE
Settings with excluded materials and agents along with an api for it [ACD-254]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#329]
Migrated from issue: [ACD-254](https://10clouds.atlassian.net/browse/ACD-254) (Task)

The user should be able to interact with the settings using natural language.

[ACD-254]: https://10clouds.atlassian.net/browse/ACD-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant

**Comment by cielecki** [comment]
Duplicate of #206
