### ISSUE TITLE
What else to move to websockets? Clean up the implementation a bit [ACD-244]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#330]
Migrated from issue: [ACD-244](https://10clouds.atlassian.net/browse/ACD-244) (Task)

[ACD-244]: https://10clouds.atlassian.net/browse/ACD-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
