### ISSUE TITLE
Adapter for materials - an ability to pull them from any source (current toml files, but also notion, package.json etc, spreadsheets etc)

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#331]
Migrated from issue: [ACD-239](https://10clouds.atlassian.net/browse/ACD-239) (Task)

[ACD-239]: https://10clouds.atlassian.net/browse/ACD-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Duplicate
