### ISSUE TITLE
Print less information about an asana task when adding it [ACD-202]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#339]
Migrated from issue: [ACD-202](https://10clouds.atlassian.net/browse/ACD-202) (Task)

[ACD-202]: https://10clouds.atlassian.net/browse/ACD-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Related to #340

**Comment by cielecki** [comment]
Subtask of #340
