### ISSUE TITLE
Ability to work with a big pdf (vectorize? create an index?)? [ACD-195]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#342]
Migrated from issue: [ACD-195](https://10clouds.atlassian.net/browse/ACD-195) (Task)

[ACD-195]: https://10clouds.atlassian.net/browse/ACD-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by DVLevin** [comment]
Meaning: 

1. I paste big material (pdf, txt with 100 pages)
2. Automatically it chunks according to the TOC (table of contents) OR Pages numbers
3. For each chunk (page) - the summary is created automatically 
3.1. as well as usage (what is in this chunk - most relevant keywords) 
4. In my material it is shown as One big FOLDER with 100 materials inside -> (for UX purpose) 
5. Inside this folder I have all the chunks to update manually if needed 

SO

From 1 Big doc I get 1 Folder (with usage as for doc) and # of Materials inside this folder, where each has a usage (instructions for an internal RAG).

**Comment by cielecki** [comment]
Duplicate of #711
