### ISSUE TITLE
[Design] Involve ziemowit to assess the current project vs the requirements / use cases they gathered [ACD-168]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#343]
Migrated from issue: [ACD-168](https://10clouds.atlassian.net/browse/ACD-168) (Process Development)

[ACD-168]: https://10clouds.atlassian.net/browse/ACD-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
