### ISSUE TITLE
[User's settings] User should have the abiity to set his avatar, name and other info via interface. [ACD-133]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#349]
Migrated from issue: [ACD-133](https://10clouds.atlassian.net/browse/ACD-133) (Task)

[ACD-133]: https://10clouds.atlassian.net/browse/ACD-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
@udislau Frontend should be already done for this

**Comment by udislau** [comment]
WIP https://github.com/10clouds/aiconsole/commit/75e9e4c4ab5bee5d36d073ca30c5f5b6d2985abe

**Comment by kgradzka** [comment]
Tested on 0.2.10-rc.1 on Win10.

User image is not getting changed after choosing image from gallery and saving it. 🔴 

https://github.com/10clouds/aiconsole/assets/61430006/e2aacbcf-9155-47bb-b593-1ccd56c3d587

After changing user's e-mail avatar was changed to something not chosen by user. 🔴 
![user_image_changed_after_editing_email](https://github.com/10clouds/aiconsole/assets/61430006/8bcc1fdd-9847-4184-bf27-8ba5f07e0ac5)
There are issues with saving all image, name and e-maill address. 🔴 

https://github.com/10clouds/aiconsole/assets/61430006/9a4ec87d-af28-4d8e-b43d-e4764ff747b9

**Comment by aga-gasinska** [comment]
problem with saving of the avatar still exists - after I save the avatar doesn't change  (checked on MacOS)

**Comment by aga-gasinska** [comment]
Checked it on v0.2.11-rc.3 and it's fine now.
