### ISSUE TITLE
[Blocked by UX] Some more controlable way of initiating a directory structure [ACD-132]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#350]
Migrated from issue: [ACD-132](https://10clouds.atlassian.net/browse/ACD-132) (Task)

Decyzja UX potrzebna: jak zarządzamy katalogami projektowymi? Np: jak jest kropka i C to jest to katalog projektu, nie tworzy przypadkowo plików w złych katalogach.,Teraz jest tak, że jak się zmieni katalog to automatycznie się tworzą pliki i katalogi powiązane z nowym projektem. Z punktu widzenia UX lepiej by było, żeby user sam podejmował decyzję, czy chce, żeby na dysku mu się tworzyły nowe pliki. Powinien system zapytać “ej tu nie ma projektu, chcesz swtorzyć nowy?”, albo nowa fukncja tworzenia nowego projektu lub dodawania z dysku już istniejącego projektu. Bardziej jasna ma być funckja tworzenia rzeczy w katalogu. , , przykład jakiejś apki, która pracuje na katalogach a nie na plikach? Trzeba poszukać. Przykładem jest github, no ale to developerski. ,either seperate "aiconsole init" and "aiconsole" commands or when the aiconsole lunches it should prompt in the interface whenever the directory should be populated with aiconsole data (or maybe choose a project directory?) 

[ACD-132]: https://10clouds.atlassian.net/browse/ACD-132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
This is old and irrelevant.
