### ISSUE TITLE
[Concept work required] Move communication to websockets so things can be sent to frontend outside of normal flow (cron activity, errors etc) [ACD-113]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#351]
Migrated from issue: [ACD-113](https://10clouds.atlassian.net/browse/ACD-113) (Task)

Chat powinien być zrobiony na websocketach w taki sposób, żeby móc dosyłać messages nie tylko w responsie na to, że user coś zrobił.  

[ACD-113]: https://10clouds.atlassian.net/browse/ACD-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
This is actually done, a follow up issue: https://github.com/10clouds/aiconsole/issues/355
