### ISSUE TITLE
Forcing Agents and Materials via Chat

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#359]
# Forcing Agents and Materials via Chat
There has been a significant change in the context of the operation of materials and agents. We can now force them from the chat level.

Here, all the states are detailed, showing what changes and what needs to be added:
[Link to Figma File with Design and Node ID](https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=2515%3A15308&mode=design&t=TC8GMvenHqXJ2yBq-1)

**Comment by cielecki** [comment]
@pwksn few issues with the current implementation:

* When an Agent is chosen, the layout breaks
<img width="336" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/f38e116b-462e-4c31-bf59-2cabec4e8cd4">
* No keyboard support when typing the material name
* No keyboard support in dropdown
* "Start writing to add" should be at the end of chosen materials
* There is a scroll bar in the sidebar on top of the normal chat list scroll bar
* I should not get chat options if there is no chat opened

**Comment by kilodilo** [comment]
If we want to have folding option than we should redesign this element. Apps doesn't allow to collapse such elements inside one sidebar, they only let to change the height of this element. If we want to collapse it like in ChatGPT it should be shown next to the sidebar like this:
![ffeff](https://github.com/10clouds/aiconsole/assets/152965457/1d4adb51-7a3d-420b-a4b2-88c5e0b9a10e)

**Comment by kilodilo** [comment]
![image](https://github.com/10clouds/aiconsole/assets/152965457/34797ddf-f3c4-4fa5-b9aa-5e7b2721090d)
 
![image](https://github.com/10clouds/aiconsole/assets/152965457/9bc183c4-0cda-4aa5-8e9c-5abf6d112390)


here are the designs for collapsing this element https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=2657%3A13063&mode=design&t=izi1hyekiVFKvZNm-1

**Comment by aga-gasinska** [comment]
@pwksn shouldn't this task be on "Ready for QA"?

**Comment by pwksn** [comment]
@aga-gasinska nope, the backend part is still missing.

**Comment by aga-gasinska** [comment]
expected beh:
https://github.com/10clouds/aiconsole/assets/155951278/5d1f04df-98a9-4105-ba4b-2767aad3f7b7

**Comment by kilodilo** [comment]
The designs are here https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=4103%3A12073&mode=design&t=YY8GsLoBDzLF7aSm-1

**Comment by AGasior** [comment]
I decided to display 3 agents and 2 rows of materials, with 4 agents and 3 rows of materials it was huge. 

<img width="1436" alt="Zrzut ekranu 2024-02-6 o 08 20 35" src="https://github.com/10clouds/aiconsole/assets/102804214/f190f78c-0a6d-4973-9568-7fb143c75f6d">

**Comment by kilodilo** [comment]
Can we use smaller font size per materials as in the design? When there's a lot of them it is quite overwhelming :D 
And I find this padding too big, can we make it smaller? 
![image](https://github.com/10clouds/aiconsole/assets/152965457/fd238798-2731-4506-81fc-3b32a47682c2)

**Comment by aga-gasinska** [comment]
combine the list of agents and materials in chat options (design update needed)

**Comment by kilodilo** [comment]
If we want to keep it simple, than we should keep it like this:
https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=4195%3A12608&mode=design&t=SbtMcLGyxcz0elfZ-1
![image](https://github.com/10clouds/aiconsole/assets/152965457/892e90fd-1730-4bb4-85f9-4811d533edf1)


1. The text in the input should be changed to "Type "@" to select a specific agent or material" (because now we can choose this OR this, not this AND this)
2. When the user use Backspace the window close, the “@” symbol is left. 
3. User should be able to use keyboard arrows to choose the agent or material.
4. Window close when the user choose one element (agent or material)

**Comment by aga-gasinska** [comment]
works fine using keyboard
