### ISSUE TITLE
Markdown is supported button for text editors

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#360]
In a similar fashion to the way GitHub does that:

<img width="236" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/bdc3ea3a-5ac3-4a51-8ef4-5ebefb2b31aa">

**Comment by kilodilo** [comment]
We can show it like this but are there specific type of text fields where it should be shown?
![image](https://github.com/10clouds/aiconsole/assets/152965457/c89f2ed2-5691-4d5a-9390-7a74a8083129)

**Comment by cielecki** [comment]
> We can show it like this but are there specific type of text fields where it should be shown? 

All that support markdown text formatting and we would like to show a help of how to format text using it.

Note: "Markdown is supported" is different than "Supported by Markdown"

**Comment by cielecki** [comment]
Reassign this to frontend once this is done.

**Comment by kilodilo** [comment]
Ok so if it is a link than we can make it like that: 
![image](https://github.com/10clouds/aiconsole/assets/152965457/3c6640cb-4b48-48b7-9583-1645bd74dfd4)

I'm moving this task further to frontend.

**Comment by jakubbilko** [comment]
@cielecki should this link to the manual also?

**Comment by cielecki** [comment]
Yes

**Comment by cielecki** [comment]
This is not good:

<img width="678" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/cc1b2674-41b1-415b-8a6a-5effe60d5183">

**Comment by kilodilo** [comment]
Yes it needs some adjustments. 
Let's add a background to the element and add a gradient below when the texts
In this case we need to make the "usage" text area slightly higher than it is now. 120px seems ok.

Here is the link -> https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=2518%3A18600&mode=design&t=MDpjRC0SeES3l3Um-1

Here are the previews:
![Uploading Console2.png…]()

**Comment by kilodilo** [comment]
Together with @jakubbilko we agreed to leave the Markdown info under the text area 


![Image](https://github.com/10clouds/aiconsole/assets/152965457/3dedce00-8cc7-4296-afc5-dc558dd0fefa)

**Comment by kgradzka** [comment]
Retested on Win10.
Markdown support is visible, link redirects to the https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax.  ✔️ 
![retest_issue_360](https://github.com/10clouds/aiconsole/assets/61430006/f9bf83ce-e42c-4e13-9ebf-8c4a885c9f00)
