### ISSUE TITLE
Too little padding on the left of a chat window

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#361]
<img width="269" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/22376d95-a42d-4ef7-848a-1fba78c66072">

**Comment by kgradzka** [comment]
Retested on the newest changes on Win10.

Corrected. ✔️ 
![issue_361_retest](https://github.com/10clouds/aiconsole/assets/61430006/dfd1c1e8-4acd-4ec9-bd01-9a3aca11560b)
