### ISSUE TITLE
Hidden button in agent editor

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#362]
<img width="211" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/7ba5470c-65d0-4ddd-b4dc-47e7b8e85b4e">

**Comment by kgradzka** [comment]
Retested on the newest changes on Win10.

Corrected. ✔️ 
![issue_362_retest](https://github.com/10clouds/aiconsole/assets/61430006/847a3a3e-a215-4054-a427-b2ca3cbae077)
