### ISSUE TITLE
Persistent ModuleNotFoundError with google-auth-oauthlib Despite Successful Installation

### ISSUE THREAD

**Issue by Odene** [10clouds/aiconsole#368]
##Issue description
We have been attempting to integrate Google Analytics 4 within our AIConsole system to enhance our data analytics capabilities. During the setup process, we are required to utilize the google-auth-oauthlib library to handle OAuth flow for Google APIs. Despite successful confirmation via pip that shows google-auth-oauthlib is installed, our Python environment fails to recognize the installed package, throwing a ModuleNotFoundError when we attempt to import it.

##Steps to reproduce

1. The necessary libraries are installed using the pip command:
2. pip install --upgrade google-auth-oauthlib google-api-python-client
3. The installation process completes without any reported errors.
4. Upon running the Python script that imports google_auth_oauthlib.flow, the following error is encountered:
5. ModuleNotFoundError: No module named 'google_auth_oauthlib'
6. Multiple attempts at reinstallation and upgrades did not resolve the issue.

##Environment details:
Python version: (Specify the Python version used)
OS: (Specify the operating system and version)
Packages: google-auth-oauthlib (confirmed installed via pip), google-api-python-client

##Attempts at resolution:
- Reinstallation of both google-auth-oauthlib and google-api-python-client.
- Verifying the package installations using pip commands.
- Ensuring the correct Python environment is active when running the script.

Would appreciate any insights or recommendations for troubleshooting this issue further.

**Comment by udislau** [comment]
This PR https://github.com/10clouds/aiconsole/pull/372 resolves an issue.

**Comment by cielecki** [comment]
This is temporary fix, this needs to be adjusted so pip executable is created on windows.

**Comment by cielecki** [comment]
Probably fixed in: https://github.com/10clouds/aiconsole/commit/9118e62af77fa26b4d8c8af42bfef0a67154bcbb (needs verification and adjustment as I don't have Windows at hand right now)

**Comment by udislau** [comment]
@cielecki code review + update https://github.com/10clouds/aiconsole/pull/471
