### ISSUE TITLE
Name of the material and Usage is fairly visually disjointed, I do not get the feeling that I'm editing the most important and key thing - the name when I edit it.

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#370]
<img width="1066" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/41364b5e-6dd9-4797-8ad3-2da78579dbaf">

**Comment by kilodilo** [comment]
When editing name of material in top bar or sidebar it should show the bounding box like this:
![wtwtwtete](https://github.com/10clouds/aiconsole/assets/152965457/feaf0560-c7a7-412a-8e6f-0fcf377ddf1f)


It can be seen here:
https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=393%3A8808&mode=design&t=izi1hyekiVFKvZNm-1

**Comment by cielecki** [comment]
@kilodilo  This is more about the fact that when interacting with the interface the title and the content seem to be about two different units of information. Because of this, when I open such screen I first think that Usage is the title of the material.

**Comment by kilodilo** [comment]
Okay, so the typography hierarchy is the problem.
I understand now ;)
We can make the material/agent title with H4 style,
and box labels as paragraph style.

Looks like this:
![image](https://github.com/10clouds/aiconsole/assets/152965457/8f11622e-705f-4d8d-bce3-78efb0d3b6c2)

**Comment by cielecki** [comment]
Looks better, I think that in the system we also have an issue with the space between title and the "usage"

**Comment by cielecki** [comment]
If those are just simple adjustments let's just implement them and verify on the live system.

**Comment by kilodilo** [comment]
Ok, here are the changes listed:
https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=2993%3A24650&mode=design&t=oLvOLw03rTdD5L2L-1
![Materal and Agent settings labels](https://github.com/10clouds/aiconsole/assets/152965457/cfcc16eb-d446-4eba-a7c4-fd5dd277c529)

Please, @pwksn check also the distances mentioned my Maciej.

**Comment by aga-gasinska** [comment]
@kilodilo please verify this issue

**Comment by kilodilo** [comment]
Yes, it is ok now :)
