### ISSUE TITLE
Incorrect names of save buttons

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#374]
<img width="404" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/7f84dbc0-cfc7-4c4b-b01a-9abfab080fad">

**Comment by aga-gasinska** [comment]
![Zrzut ekranu 2024-02-2 o 11 20 53](https://github.com/10clouds/aiconsole/assets/155951278/fac3e9e0-9672-406b-8699-274acc8d9896)
