### ISSUE TITLE
Resizing the startup screen and headers - responsive [ACD-879]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#379]
Migrated from issue: [ACD-879](https://10clouds.atlassian.net/browse/ACD-879) (Task)

Hello, we need to refine the scaling of the elements on the start screen. Currently, when we have a small window displayed, it looks bad. It's mainly about these tiles. I have written down how they should scale. I also changed the spacing a bit.

Here I have also outlined the changes to the size of H1 depending on the response:

[ACD-879]: https://10clouds.atlassian.net/browse/ACD-879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by AGasior** [comment]
I checked startup screen and we have RWD implemented 

<img width="1149" alt="Zrzut ekranu 2024-01-10 o 10 26 54" src="https://github.com/10clouds/aiconsole/assets/102804214/ad1ea557-75a5-4231-a11c-210bbeb7e900">

<img width="989" alt="Zrzut ekranu 2024-01-10 o 10 26 35" src="https://github.com/10clouds/aiconsole/assets/102804214/24d45cdb-ed43-43c1-a3ee-ab04c1f65ec5">

<img width="707" alt="Zrzut ekranu 2024-01-10 o 10 27 35" src="https://github.com/10clouds/aiconsole/assets/102804214/ef772049-0469-4bc4-ae0c-adf289ea01bd">

<img width="578" alt="Zrzut ekranu 2024-01-10 o 10 26 03" src="https://github.com/10clouds/aiconsole/assets/102804214/0e6046ec-c9cd-4b94-ab83-176a6b05e5e0">

**Comment by aga-gasinska** [comment]
checked and elements of the startup screen are resizing correctly
