### ISSUE TITLE
AIConsole Use case videos [ACD-868]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#383]
Migrated from issue: [ACD-868](https://10clouds.atlassian.net/browse/ACD-868) (Task)

[ACD-868]: https://10clouds.atlassian.net/browse/ACD-868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
