### ISSUE TITLE
Image generation [ACD-865]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#384]
Migrated from issue: [ACD-865](https://10clouds.atlassian.net/browse/ACD-865) (Task)

[ACD-865]: https://10clouds.atlassian.net/browse/ACD-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Duplicate of #291
