### ISSUE TITLE
aiconsole.ai - user downloaded wrong binary by clicking the download button (the nu package instead of exe) on windows [ACD-822]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#387]
Migrated from issue: [ACD-822](https://10clouds.atlassian.net/browse/ACD-822) (Bug)

[ACD-822]: https://10clouds.atlassian.net/browse/ACD-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kgradzka** [comment]
Retested on Win10. 
After choosing "Picked for you: Windows" .exe version is downloaded. ✔️ 
![retest_issue_387](https://github.com/10clouds/aiconsole/assets/61430006/1541ae17-f6cd-4cef-8275-84942c7b8002)
