### ISSUE TITLE
Errors on Windows [ACD-813]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#389]
Migrated from issue: [ACD-813](https://10clouds.atlassian.net/browse/ACD-813) (Bug)

Reported by user on Discord ,  

[ACD-813]: https://10clouds.atlassian.net/browse/ACD-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by aga-gasinska** [comment]
wirtual machines with Windows needed for @pbaranski9411 and @udislau to reproduce errors

**Comment by aga-gasinska** [comment]
@khdevel provided Windows host

**Comment by udislau** [comment]
Fixed
