### ISSUE TITLE
Chat view should not get obstructed [ACD-784]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#394]
Migrated from issue: [ACD-784](https://10clouds.atlassian.net/browse/ACD-784) (Bug)

There’s a lot of explanation of what AI does - it obstructs the view of the last command/chat. I can’t check what I written because of that.,In my opinion this window should have it’s own space (with it’s own scrolling and limited height) that does not obstruct chat. 

[ACD-784]: https://10clouds.atlassian.net/browse/ACD-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Already fixed
