### ISSUE TITLE
Errors when opening or creating new project [ACD-778]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#395]
Migrated from issue: [ACD-778](https://10clouds.atlassian.net/browse/ACD-778) (Bug)

Hey, AiConsole shows these errrors each time I add new project or open it.  

[ACD-778]: https://10clouds.atlassian.net/browse/ACD-778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by pbaranski9411** [comment]
To be tested by @kilodilo ;)

**Comment by kilodilo** [comment]
Done, it's fine already

**Comment by kilodilo** [comment]
Done, it's fine already
