### ISSUE TITLE
BE needed [ACD-731]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#400]
Migrated from issue: [ACD-731](https://10clouds.atlassian.net/browse/ACD-731) (Sub-task)

[ACD-731]: https://10clouds.atlassian.net/browse/ACD-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
