### ISSUE TITLE
[Hard to reproduce] Error indentation [ACD-725]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#401]
Migrated from issue: [ACD-725](https://10clouds.atlassian.net/browse/ACD-725) (Bug)

Czasami jak się kod wygeneruje to pojawia się error indentation. Do zbadania, dzieje się to co pewien czas, trzeba próbować generować kod, bo nie wiadomo kiedy się to odpala.  

[ACD-725]: https://10clouds.atlassian.net/browse/ACD-725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Fixed
