### ISSUE TITLE
Error generating empty code [ACD-724]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#402]
Migrated from issue: [ACD-724](https://10clouds.atlassian.net/browse/ACD-724) (Bug)

Sometimes the Console generates empty code and runs it, it doesn't work out and only then it starts to write it normally

[ACD-724]: https://10clouds.atlassian.net/browse/ACD-724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Is this still a thing?

**Comment by cielecki** [comment]
Yes

<img width="537" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/c4656b5a-4c96-49d9-89ac-45554af2cdc9">

<img width="616" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/e657523a-f811-461d-9b0e-06c48620f992">
