### ISSUE TITLE
Using usage_examples in tutorial for the user (Assistant bot) [ACD-564]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#410]
Migrated from issue: [ACD-564](https://10clouds.atlassian.net/browse/ACD-564) (Task)

[ACD-564]: https://10clouds.atlassian.net/browse/ACD-564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
They are on the main empty screen
