### ISSUE TITLE
[Concept work required] Building a full replacement for assistant API? [ACD-524]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#412]
Migrated from issue: [ACD-524](https://10clouds.atlassian.net/browse/ACD-524) (Story)

[ACD-524]: https://10clouds.atlassian.net/browse/ACD-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
