### ISSUE TITLE
[IDEA] automatic sumarization of chats when the token limit is reached [ACD-457]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#416]
Migrated from issue: [ACD-457](https://10clouds.atlassian.net/browse/ACD-457) (Task)

[ACD-457]: https://10clouds.atlassian.net/browse/ACD-457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
No longer relevant
