### ISSUE TITLE
[Hosted] Log in

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#419]
Migrated from issue: [ACD-419](https://10clouds.atlassian.net/browse/ACD-419) (Task)

[ACD-419]: https://10clouds.atlassian.net/browse/ACD-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Duplicate of #438
