### ISSUE TITLE
[Hosted] Registration

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#420]
Migrated from issue: [ACD-418](https://10clouds.atlassian.net/browse/ACD-418) (Task)

[ACD-418]: https://10clouds.atlassian.net/browse/ACD-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Duplicate of #438
