### ISSUE TITLE
Check if there is a loop inside interpreter and maybe remove it in the context of director [ACD-226]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#432]
Migrated from issue: [ACD-226](https://10clouds.atlassian.net/browse/ACD-226) (Sub-task)

[ACD-226]: https://10clouds.atlassian.net/browse/ACD-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
I don't remember what this is about
