### ISSUE TITLE
[BE] Proper Python manual for materials and agents manipulation [ACD-212]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#434]
Migrated from issue: [ACD-212](https://10clouds.atlassian.net/browse/ACD-212) (Task)

Proper Python API for materials manipulation - It's about having an API type material that allows for manipulation of materials, to be fully featured, saving, re-naming.

[ACD-212]: https://10clouds.atlassian.net/browse/ACD-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Ability to create an agent

**Comment by cielecki** [comment]
przadka
OP
 — 31/12/2023 06:39
Agents descriptions can be quite lengthy and specific. It would be great to have a meta-agent who is able to create other agents based on simple instructions from users, guiding them through the process via a conversation (similarly to how OpenAI GPTs are created now)

**Comment by Globarti** [comment]
The way I see this work is to review the conversation, store the most important data in a form of a note (python note / connection / Skill). The importance here is to have a certain procedure that would work in multiple case scenarios and store the notes. 

It could be stored in a form of a MATERIAL but i guess much more efficient way to make it would be an AGENT that would be called whenever user wants to store the material. It could be an "AIConsole AGENT" with multiple capabilities connected to self improvement. 


How i envision prompt:

You are an expert code instructor. You can summarise a discussion between people in a logical and step by step manner. Your goal and purpose is to recover most of information from discussion in such a way that the final effect can be replicate by anyone. You are extremely logical. You understand the connection between natural language and final output code.

0. You will be given a conversation between a USER and Language model. In this conversation user is asking the Language model for some task execution.

1. Store a user command in a most generic way. Save it in a way you could recognise it in future when asked about same taks in any context directly or indirectly. Prepare a paraphrase of a command that could cover other situation when this instruction could work that triggers the same process later.  Store it in a material field <usage instruction>

2. Summarise the above and write a name of Material. It should be a one sentence description of what this material instructs to.

4. Summarise the steps made to accomplish the user command. Describe ONLY the successful attempt. Write a clear instruction between user input and the successful code output.

5. Summarise what steps were not successful. Write why they been unsuccessful in a step by step manner. Highlight that this has not brought no success for a user and that next usage of this material should prevent this method and go straight to a successful one.

6. Store it in a MATERIAL folder of AIConsole



The above is EXAMPLE of a procedure the AIC could go threw. 
It could be solved in different way but the above description shows my intention to anable auto generating the notes after successfull coding sessin with AIC.

**Comment by Globarti** [comment]
Also I would love to be able to edit the prompt of my Proxy-Agent AND generate new Agents and Materials on my command. 
I would like this command to work: 

"Generate a serp search for X and after success store the instruction to this project for further use."
