### ISSUE TITLE
After I click an agent portrait I can edit that agent [ACD-140]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#443]
Migrated from issue: [ACD-140](https://10clouds.atlassian.net/browse/ACD-140) (Task)

  

[ACD-140]: https://10clouds.atlassian.net/browse/ACD-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
Not sure if that is even still relevant?

**Comment by kilodilo** [comment]
> Not sure if that is even still relevant?

No, it's not. This task is closed in Jira
