### ISSUE TITLE
Blocking side-effects during rendering [ACD-48]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#451]
Migrated from issue: [ACD-48](https://10clouds.atlassian.net/browse/ACD-48) (Task)

[ACD-48]: https://10clouds.atlassian.net/browse/ACD-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
This is no longer relevant.
