### ISSUE TITLE
[GenUI] [FE] Output type support with react (or html) components [ACD-43]

### ISSUE THREAD

**Issue by Rafal80** [10clouds/aiconsole#455]
Migrated from issue: [ACD-43](https://10clouds.atlassian.net/browse/ACD-43) (Task)

On FE you need to do output type support with react (or html) components 

[ACD-43]: https://10clouds.atlassian.net/browse/ACD-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by cielecki** [comment]
This is done
