### ISSUE TITLE
Tool call moves slightly up after name is established

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#456]
<img width="425" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/7c486a55-7a71-4396-9eef-122853e094f4">

<img width="516" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/e9fef00f-3401-4e2d-8dcb-e4d54041949b">

**Comment by AGasior** [comment]
@cielecki I checked it and I didn't notice cursor is going up after name established. But I noticed something different behavior. When response is rendering for small amount of time user see editor buttons, but without content which can edit.
  
<img width="959" alt="Zrzut ekranu 2024-01-4 o 13 28 28" src="https://github.com/10clouds/aiconsole/assets/102804214/5bdd1f05-7f5b-4a44-8014-4159d5b4a484">

**Comment by cielecki** [comment]
Yeah, the behavior reported was happening before the the recent changes, this seem not to apply anymore.
