### ISSUE TITLE
Text area clipping in materials editor

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#458]
<img width="616" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/014aec66-d1d5-42c4-a83d-37fe1fa84253">

**Comment by aga-gasinska** [comment]
It works fine. 
<img width="1120" alt="Zrzut ekranu 2024-01-16 o 12 17 33" src="https://github.com/10clouds/aiconsole/assets/155951278/44002ed8-d316-4733-9d12-8bd461b33e93">
