### ISSUE TITLE
Generation of tool usage, sometimes is not streaming and waits for the full code

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#459]
<img width="766" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/b51dca04-a8a7-4949-ad9e-d0ad4164aa77">

**Comment by cielecki** [comment]
@pbaranski9411 Maybe you can take it, its in the same code you worked on?

This is mostly happening when there are multiple tool usage requests being generated at the same moment.

**Comment by pbaranski9411** [comment]
@cielecki I think I won't be able to do it anymore because tomorrow I'm leaving the project and it's not critical one

**Comment by udislau** [comment]
@aga-gasinska Would you plz check this? Deployed to https://github.com/10clouds/aiconsole/releases/tag/v0.2.11-rc.3

**Comment by aga-gasinska** [comment]
Checked it on MacOS and it's fine. Checked it with one task and multiple tasks and each time the code was streaming without any lags.
