### ISSUE TITLE
Creation of venv (creating projects) takes so long that requests time out and we are stuck on the project screen

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#460]
https://github.com/10clouds/aiconsole/assets/101296/1f53642a-f8a3-46ce-b79a-3097e805413e

**Comment by cielecki** [comment]
Only when run as a web server with web frontend

**Comment by pbaranski9411** [comment]
To test it just create a new project

**Comment by pbaranski9411** [comment]
Two ways:
1. Make sure that this never times out (frontend)
2. Venv should happen in the background (not block everything)
3. Verification when venv is done

**Comment by udislau** [comment]
@cielecki Here is the solution that current state of #602 provides. I will work on design and logic with @kilodilo and @AGasior 

https://github.com/10clouds/aiconsole/assets/30052145/6a142d6c-11bb-4f37-8136-d3a38285b3af

**Comment by udislau** [comment]
Send only one message
