### ISSUE TITLE
We probably need to refresh venvs with each release, how to do that properly?

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#462]
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by udislau** [comment]
@cielecki https://github.com/10clouds/aiconsole/pull/522.

New python bundled -> reconstruct the venv for a given project, all user dependencies are kept in .aic/requirements.txt and logged there with each run of `pip install`

**Comment by udislau** [comment]
By the way found a new interesting issue. After project rename venv breaks (links for python and pip are not relative, they are absolute). 

Solution could be to move all venvs to the Application Support folder 🤔
