### ISSUE TITLE
Analysis should be moved on top of the chats list window and be integrated with the panel for managing the chat settings

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#463]

**Comment by kilodilo** [comment]
The analysis can be moved to the top and have an option like "Hide"
In Chat options there can be the checkbox "Let AI show it’s analysis process" that can be marked down or not.
![Console](https://github.com/10clouds/aiconsole/assets/152965457/20509480-3f54-4daa-9db4-d2fd8317fb60)

**Comment by cielecki** [comment]
Experimentaly I have readded it to the messages themselves, let's verify if that works, if not - let's experiment with moving it to the top or to the side bar.

**Comment by cielecki** [comment]
Duplicate of #503
