### ISSUE TITLE
Edit buttons are too tightly packed and possibly too small

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#465]
<img width="232" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/89430115-75ac-49ee-82fb-d4739891944b">

**Comment by cielecki** [comment]
The size is now correct but the edit window should be bigger and right next to the buttons, what co you think @kilodilo ?

**Comment by kilodilo** [comment]
We should keep the size of the editing box as it is because it is the size of our text area. We only want to change the icons to these, consistent with out icon styles:
![image](https://github.com/10clouds/aiconsole/assets/152965457/1e5a1309-7b66-4cbb-91a7-b649cbdafade)

**Comment by kgradzka** [comment]
Retested on Win 10 together with https://github.com/10clouds/aiconsole/issues/226. 

Icons were changed. ✔️ 
![retest_issue_465](https://github.com/10clouds/aiconsole/assets/61430006/c87da13d-ae59-4ef5-8810-d9068279f88d)
