### ISSUE TITLE
Preview on AIConsole material has the preview button outside of the window

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#467]
<img width="1147" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/bf56d984-3425-4413-9331-f046a3a86c6f">

**Comment by kgradzka** [comment]
Retested on Win10.

Button placement corrected. ✔️ 
![issue_467_retest](https://github.com/10clouds/aiconsole/assets/61430006/61cc1950-4dc6-416b-8685-8117df7eca19)
