### ISSUE TITLE
Linux versions hang during start-up

### ISSUE THREAD

**Issue by tmuras** [10clouds/aiconsole#468]
During the start-up, the console hang.
I have checked versions:
AIConsole-linux-x64-0.2.7.zip
AIConsole-linux-x64-0.2.9.zip

strace is showing that aisonsole is reading from pipe and sockets, in a loop, indefinitely:
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=43, events=POLLIN}, {fd=44, events=POLLIN}, {fd=78, events=POLLIN}], 5, 0) = 0 (Timeout)

![image](https://github.com/10clouds/aiconsole/assets/695281/c0877024-46ab-4f6f-a791-bd7c981a3151)

Windows version 0.2.9 works OK for me.

**Comment by kgradzka** [comment]
I've tried to reproduce this on my VM with Ubuntu but both versions (0.27 & 0.2.9) work for me, I can open them without any issues. 
https://github.com/10clouds/aiconsole/assets/61430006/cc3aab66-8527-45c8-87ff-24ac93dbe08a

@tmuras what Linux distribution are you using?

**Comment by kgradzka** [comment]
I've tried to reproduce this on my VM with Ubuntu but both versions (0.27 & 0.2.9) work for me, I can open them without any issues.
https://github.com/10clouds/aiconsole/assets/61430006/cc3aab66-8527-45c8-87ff-24ac93dbe08a

@tmuras what Linux distribution are you using?
