### ISSUE TITLE
Use Zod schemas to validate incoming data from server

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#473]

**Comment by jakubbilko** [comment]
I think this needs a bit of discussion on how we structure the API functions in the project. There are a few issues at the moment:
- we don't have a standard way of doing these functions (some include checks/transformations, some don't)
- Some of the request functions are just wrappers around websockets
- Some of them have try/catch blocks in them

I think we should come up with a standardized way of creating API calls
