### ISSUE TITLE
How to remove old commit message from the repo?

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#475]

**Comment by ugsto** [comment]
For removing or editing old commit messages, it's possible to use `git rebase` or `git filter-branch --env-filter`. However, it's important to note that these operations rewrite the repository's history. Consequently, if you push these changes to a repository, you will need to use `--force`. This action can disrupt the history for others and is generally discouraged, especially in shared or public repositories (like this one). 

If the commit in question is not in a public repository or hasn't been shared with others, the risk is lower. However, it's still crucial to proceed with caution. 

For editing or removing commit messages, an interactive rebase (`git rebase -i <COMMIT_HASH>^1`) is often used. It provides more control over individual commit messages. I can guide you through this process if you're not familiar with it.

Given the risks associated with rewriting history, I recommend considering whether this operation is absolutely necessary. If the issue with the commit is minor, adding a new commit to correct or clarify the previous one might be a safer option.

**Comment by aga-gasinska** [comment]
@cielecki is it still valid?

**Comment by aga-gasinska** [comment]
@cielecki have you seen the comment left by @ugsto ? Is this issue still valid?
