### ISSUE TITLE
Reimplement automatic further processing after code execution

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#476]
if (data.stage === 'end') {
      useChatStore.getState().editToolCall((toolCall) => {
        toolCall.is_executing = false;
      }, data.id);

      useChatStore.getState().finishProcess(data.request_id, false);
      const chat = useChatStore.getState().chat;

      //if all code in the current message is ran, continue operation with the same agent
      const toolCallLocation = getToolCall(chat, data.id);
      const lastMessage = getLastMessage(chat);

      const message = toolCallLocation?.message;

      if (message?.id === lastMessage?.message.id) {
        // if all tools have finished running, continue operation with the same agent
        const finishedRunnigCode = message?.tool_calls.every(
          (toolCall) => toolCall.is_executing === false && toolCall.output !== undefined,
        );

        if (finishedRunnigCode) {
          await useChatStore.getState().doExecute(); // Resume operation with the same agent
        }
      }
    }

**Comment by kgradzka** [comment]
@cielecki how this can be retested?

**Comment by aga-gasinska** [comment]
after the code is executed there should be answers

**Comment by kgradzka** [comment]
Testing blocked by: https://github.com/10clouds/aiconsole/issues/636.

**Comment by kgradzka** [comment]
Retested on: [v0.2.10-rc.6](https://github.com/10clouds/aiconsole/releases/tag/v0.2.10-rc.6) on Win10. 

Fixed. ✔️ 
![retest_issue_476_2](https://github.com/10clouds/aiconsole/assets/61430006/e4019cba-3519-4084-9e97-adefabb7ac49)
![retest_issue_476_1](https://github.com/10clouds/aiconsole/assets/61430006/9b53b980-50f2-44a3-bff7-af6aace37c86)
