### ISSUE TITLE
Implement accepting code in frontend and backend

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#481]

**Comment by cielecki** [comment]
The run and always run buttons show up before the finalization of the code

**Comment by AGasior** [comment]
resolve we this PR [617](https://github.com/10clouds/aiconsole/pull/617)

**Comment by kgradzka** [comment]
@AGasior how can I retest this? is it only about "The run and always run buttons show up before the finalization of the code" mentioned in previous comment? So that run and always run button should be visible always only finalization of the code?

**Comment by AGasior** [comment]
User should be able to use buttons "run" and "always run" after finalization of the code.

**Comment by kgradzka** [comment]
Retested on [v0.2.10-rc.6](https://github.com/10clouds/aiconsole/releases/tag/v0.2.10-rc.6)

"Run" and "Always Run" buttons are visible only after finalization of the code. ✔️ 
![retest_issue_481](https://github.com/10clouds/aiconsole/assets/61430006/5eeebe5d-9898-483f-9b7b-266fae91f079)
