### ISSUE TITLE
Reloading frontend page causes settings related error

### ISSUE THREAD

**Issue by pbaranski9411** [10clouds/aiconsole#483]
<img width="1395" alt="Screenshot 2024-01-02 at 11 39 48" src="https://github.com/10clouds/aiconsole/assets/121805402/edd28b91-32d3-4bf7-be4f-66790d865401">

**Comment by pbaranski9411** [comment]
Right now I can't reproduce it

**Comment by aga-gasinska** [comment]
@pbaranski9411 could you please recheck it again if you can reproduce it this time?

**Comment by pbaranski9411** [comment]
Nope, I can't. It's working properly after @udislau changes I think. I'm closing it ;)
