### ISSUE TITLE
Error when creating new project

### ISSUE THREAD

**Issue by pbaranski9411** [10clouds/aiconsole#485]
Error from http://localhost:8000/api/projects/is_project:

```
{
    "detail": [
        {
            "type": "missing",
            "loc": [
                "body",
                "directory"
            ],
            "msg": "Field required",
            "input": {},
            "url": "https://errors.pydantic.dev/2.5/v/missing"
        }
    ]
}
```

**Comment by cielecki** [comment]
It seems like the whole is_project / choose implementation is quite messy, as is_project is showing the Open Directory dialog , it should probably be split into 3 endpoints, and on the frontend either electron or python dialog should be shown depending on availability.

**Comment by cielecki** [comment]
<img width="723" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/22df9296-bc39-4b0c-92f9-3f252e036a67">
