### ISSUE TITLE
Icon becomes very small

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#488]
<img width="626" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/b1f14220-5874-49f0-963e-14ee4d529784">

**Comment by kgradzka** [comment]
Retested on Win. 

Corrected. ✔️ 

https://github.com/10clouds/aiconsole/assets/61430006/0ae49a81-1175-43cd-aa99-ebfe0528749f
