### ISSUE TITLE
Avatar issue

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#489]
<img width="481" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/49b2034d-9f5f-4c5f-bbad-6d7bde5c2db1">

**Comment by udislau** [comment]
https://github.com/10clouds/aiconsole/pull/490

Currently, there is a placeholder for users who haven't set up their email and username. Later, [Issue #251](https://github.com/10clouds/aiconsole/issues/251) will introduce improved options. We need to integrate the setup of email and username on the front end.

<img width="437" alt="Screenshot 2024-01-02 at 19 43 30" src="https://github.com/10clouds/aiconsole/assets/30052145/2516232a-b9a8-4a49-b967-6916bb09075b">

**Comment by cielecki** [comment]
Added comments to the pull request

**Comment by udislau** [comment]
Resolved in ae5a7329faf42099a9c8a8ecade002afdad689a2
