### ISSUE TITLE
Installation icon on Macos is same as app icon 

### ISSUE THREAD

**Issue by Globarti** [10clouds/aiconsole#496]
## Expected Behavior

When installing from .dmg there should be a installatuon icon (looking like a drive containing the AIC). to differenciate the installation process from the app itself.

## Actual Behavior

Icon of a drive is same as app icon.
<img width="801" alt="Screenshot 2024-01-03 at 09 55 43" src="https://github.com/10clouds/aiconsole/assets/1726746/4c3ce3af-9b43-4c3e-8583-a370adce6ac1">

## Steps to Reproduce the Problem

1. Download AIC.dmg 
2. Click .dmg
3. Go the desktop to see, that the installer icon is not "drive looking"

## Specifications

- Version: 0.2.9
- Platform: Macos

**Comment by kilodilo** [comment]
Ok, I've made the installation app. 
Here is the package for MacOS and Windows. I suppose Linux can use the same icon
I
[App Installation Icon.zip](https://github.com/10clouds/aiconsole/files/13829264/App.Installation.Icon.zip)
t is here

**Comment by pbaranski9411** [comment]
I'm not sure who can upload it, but as far as I understand it's something that is on some storage ;) So maybe let's leave it for @cielecki or our DevOps if needed :)

**Comment by cielecki** [comment]
For the electron stuff I would assume front end guys, @jakubbilko was doing electron stuff so far.

**Comment by kgradzka** [comment]
As I don't have device with MacOS I'm not able to retest this, @Globarti can you verify this change on your device when possible and confirm here with appropriate comment?

**Comment by kilodilo** [comment]
As far as I've checked it works now (checked on Windows)

**Comment by aga-gasinska** [comment]
<img width="741" alt="Zrzut ekranu 2024-01-16 o 09 16 57" src="https://github.com/10clouds/aiconsole/assets/155951278/02911439-a7a2-41fc-9b8f-aae7b2a611d0">
It works fine on MacOS
