### ISSUE TITLE
Based on ServerMessages the client should be able to deduce whenever a given processing request has terminated or not, even if there was an error.

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#501]

**Comment by cielecki** [comment]
On the front-end this requires a rewrite of sendMessageAndWaitForResponse to include negative scenarios.

**Comment by pbaranski9411** [comment]
For example when we are waiting for opened chat and this chat not exists, it will take forever.

It happens here:
https://github.com/10clouds/aiconsole/blob/1684d55bf93413de58ac6ac8944d714a841fef54/frontend/src/api/api/EditablesAPI.ts#L66
