### ISSUE TITLE
Users may become frustrated upon seeing a file path when they click to view the content of a material. Currently, we can only offer a preview, but for future, it would be a good idea to embed an editor into the app. Code is good.

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#502]
@cielecki Users may become frustrated upon seeing a file path when they click to view the content of a material. Currently, we can only offer a preview, but for future, it would be a good idea to embed an editor into the app. Code is good.

<img width="1172" alt="Screenshot 2023-12-31 at 13 25 12" src="https://github.com/10clouds/aiconsole/assets/30052145/29c4d78e-6019-49fd-8b22-f3dde297bbe1">

_Originally posted by @udislau in https://github.com/10clouds/aiconsole/issues/291#issuecomment-1872937583_

**Comment by aga-gasinska** [comment]
probably we should show the files content 

How to enable link's edition to the file -> to be solved

**Comment by aga-gasinska** [comment]
hide the linking functionality from the user

**Comment by kilodilo** [comment]
maybe we can add something like this "Upload module file" and it will uplooad the module into the Text area below
![image](https://github.com/10clouds/aiconsole/assets/152965457/eafbb369-2728-488b-b914-6464660fe64b)
@udislau ?

Figma https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=3711%3A25818&mode=design&t=hvwrMtgRs89tw1qY-1

**Comment by cielecki** [comment]
The user currently could just paste the file content in and get the same effect

**Comment by cielecki** [comment]
I would say that we should implement it in the following way:
* Under the hood all materials can be linked, this is not shown to the user
* If a material is overridden due to an edit in the UI, it will override as a non linked version
* If a linked version exists in the project, the user when editing contents will edit the linked file instead. (A user can create a linked version manually, and the only way to create and edit the link itself is through manual editing of files)

**Comment by cielecki** [comment]
@kilodilo what do you think? If it's ok it can go into development

**Comment by kilodilo** [comment]
Okay but how the user links the specific file? Where is the AIC he should have this option @cielecki

**Comment by cielecki** [comment]
Duplicate of #799
