### ISSUE TITLE
Verify that editing messages works, fix if needed (in chat interface)

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#510]
This needs to use userChatMutate

**Comment by pbaranski9411** [comment]
I tested it and I think it's working fine. Moving to QA

**Comment by pbaranski9411** [comment]
Please check generated code by AI (for example "Run factorial of 5") and change this code and run it again

**Comment by kgradzka** [comment]
Currently blocked by: https://github.com/10clouds/aiconsole/issues/636

**Comment by kgradzka** [comment]
Retested on: [v0.2.10-rc.6](https://github.com/10clouds/aiconsole/releases/tag/v0.2.10-rc.6) on Win10. 

After prompting agent with "calculate factorial of 6" appropriate code was generated. Then after deleting code output and editing Python code with different number again correct output was calculated but message below still stated that user was calculating factorial of 6. In other scenario after calculating factorial of 6 and then editing it to factorial of 7 output still shows calculated factorial of 6.
Examples:
![retest_issue_510](https://github.com/10clouds/aiconsole/assets/61430006/fd5512cc-c4bf-4974-879a-278f0504d986)
![retest_issue_510_2](https://github.com/10clouds/aiconsole/assets/61430006/4fc91a1f-c00e-491f-b7aa-a8828267696d)

@jakubbilko @udislau can you verify it again?
