### ISSUE TITLE
Invalid material midjourney_v6_prompting_guide 'charmap' codec can't decode

### ISSUE THREAD

**Issue by kgradzka** [10clouds/aiconsole#514]
After opening any project errors are visible: 
"Invalid material midjourney_v6_prompting_guide 'charmap' codec can't decode byte 0x98 in position 291: character maps to <undefined>"

![invalid_midjourney_materials_errors](https://github.com/10clouds/aiconsole/assets/61430006/0f8e3ba7-755f-4bf9-be8e-5dac3dfbfd9c)

**Comment by udislau** [comment]
Fixed in https://github.com/10clouds/aiconsole/pull/676
