### ISSUE TITLE
You can close settings without saving

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#523]
... and without any information that they are not saved

Furthermore, the changes you made persist in that window.

This is super confusing as one might think that he changed those and then get reassurance by clicking that again.

Change:
- Have a standard modal notifying about unsaved changes
- Reset the values in the modal if the user left it and returned to it again.

**Comment by aga-gasinska** [comment]
Modal appears if you close without saving and the input is cleared.
