### ISSUE TITLE
Unable to discard changes made

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#525]
How to reproduce:
1. Open a note
2. Edit part of that note
3. Switch to chats
4. Try to open chat
5. A modal pops up about unsaved changes saying "Close" or "Save" If I click close the changes are still applied.

BTW: Shouldn't the buttons be: "Back" and "Discard" ?

**Comment by kilodilo** [comment]
This message is asking the user if he wants to close unsaved project - if he clicks on "Close" button he should loose his changes. If it doesn't work this way than we should fix it.
![image](https://github.com/10clouds/aiconsole/assets/152965457/55f3be46-0c54-4528-98d0-2d7774cf4944)

But if you think this may mislead the user... maybe we should change the modal to this one used by Chrome:
![image](https://github.com/10clouds/aiconsole/assets/152965457/36827b2f-bafa-48e2-944b-6287ad2f62c9)

**Comment by cielecki** [comment]
What does the Save button does then?

**Comment by kilodilo** [comment]
Currently:
Save button saves the changes and close the window.
Close button discard changes and close the window.

**Comment by kilodilo** [comment]
Ok, let's change it to this solution than:
https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=2126%3A16815&mode=design&t=oLvOLw03rTdD5L2L-1
![image](https://github.com/10clouds/aiconsole/assets/152965457/a4ed5ffb-1c9a-4b72-aa9b-19633e705936)

**Comment by kgradzka** [comment]
@AGasior "Close" button is still visible in the newest version of AIConsole, it should be changed to "Cancel" as it is on Figma.

**Comment by kgradzka** [comment]
Retested on Win10.

Corrected. ✔️ 
![retest_issue_525](https://github.com/10clouds/aiconsole/assets/61430006/0bee3a86-aa15-4b8e-95fa-b32a7a9d0852)
