### ISSUE TITLE
Give ability to switch to other chat

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#526]
- Don't show that unsaved changes dialog for chats when an answer is being generated by the system
- Allow the user to switch
- Ask only about unsaved changes if they put something in the command input

the backend already supports generating the message by itself on the backend side

**Comment by kilodilo** [comment]
We resolved this problem in the other issue: https://github.com/10clouds/aiconsole/issues/525#issuecomment-1880915622
Does it solve the problem you have? :)

**Comment by AGasior** [comment]
When user wants to change chat during generating response, user receives loading screen, it is visible until message is generated from previous chat. 

<img width="1438" alt="Zrzut ekranu 2024-01-11 o 08 39 40" src="https://github.com/10clouds/aiconsole/assets/102804214/cdad696f-b934-42fb-9e4a-332cf9c269ae">


<img width="601" alt="Zrzut ekranu 2024-01-11 o 08 40 03" src="https://github.com/10clouds/aiconsole/assets/102804214/accfc4f5-d32c-43cb-be5f-24dc813ffe22">

**Comment by kilodilo** [comment]
Maybe add it as a new bug issue and assign to some dev :)
