### ISSUE TITLE
Code in tool calls is being streamed in one chunk instead of being streamed as the tokens show up

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#527]
<img width="477" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/a8e1addd-409d-41d2-a873-f64d4da5bfae">

**Comment by cielecki** [comment]
Furthermore, is_streamed mutations are not being generated

**Comment by cielecki** [comment]
This should be fixed with https://github.com/10clouds/aiconsole/commit/e01df89b28a5209e752409ad5bbd6dd8ed74df4e

**Comment by aga-gasinska** [comment]
@udislau can you check it?
