### ISSUE TITLE
Overwrite agent on "Execution mode" change

### ISSUE THREAD

**Issue by pwksn** [10clouds/aiconsole#542]
## Expected Behavior
The **Overview** button is enabled once the user changes the agent's execution mode.
![image](https://github.com/10clouds/aiconsole/assets/63242859/1419c05b-7917-4958-8f02-36c22d74f4aa)

## Actual Behavior
The button is disabled after the change.

**Comment by kgradzka** [comment]
Retested on [v0.2.10-rc.6](https://github.com/10clouds/aiconsole/releases/tag/v0.2.10-rc.6) on Win10.

Fixed. ✔️
