### ISSUE TITLE
Concept Needed: IDEA for MARKETPLACE of connections, models, materials and agents

### ISSUE THREAD

**Issue by Globarti** [10clouds/aiconsole#560]
The idea is to have a NOTION like TEMPLATE / MARKETPLACE spot, where you can downoad all the additional content to AIConsole projects. The most important part is that you can just "download" and have the readymade components of your AIC project. 

![image](https://github.com/10clouds/aiconsole/assets/1726746/df754a5d-f2e0-4913-8ad9-0384e22000bf)

### 1. CONNECTIONS (idea author is https://github.com/Odene)
// possibility to connect with a massive amount of external services via api configuration.  

 ->After clicking in "connections" you see a list filled with LOGOS of services we can connect to. Way it could look like: 
 ![image](https://github.com/10clouds/aiconsole/assets/1726746/1e4b0a21-0fc1-436f-ad56-b9094c61427a)

 -> showing what is connected per project in a very nice ux way. Way it could look like: After clicking on a PLUS it could show a list of all options to coose from like: 
![image](https://github.com/10clouds/aiconsole/assets/1726746/10a20a21-acd4-45a6-9f23-49b6942551eb)

 -> an animation of connecting to a given service - _It should be mega nice and satisfying effect,_ 
![a4dae5cf6e165df96e5cf975bf6bb8fe](https://github.com/10clouds/aiconsole/assets/1726746/26d57e0f-6ff7-4b91-bccc-f99da8973ef2)

### 2.Possibility to download additional models like in [JAN.AI](url)

You click on the right on the HUB button:
<img width="1191" alt="image" src="https://github.com/10clouds/aiconsole/assets/1726746/f973c12c-7d44-40f2-9752-35ebe7788eb6">

And it brings you to the list of pre setup models:
<img width="1202" alt="image" src="https://github.com/10clouds/aiconsole/assets/1726746/0d59e377-9e29-4869-8804-586fab478788">

### 3.Possibility to download pre-made MATERIALS and AGENTS
-> Same idea as above
-> It would be nice to have a short landing page with e description for a material. 

Example from the JAN:
<img width="893" alt="Screenshot 2024-01-09 at 12 57 02" src="https://github.com/10clouds/aiconsole/assets/1726746/d1d30475-0aa3-4ad0-bd55-e0177f433673">

@kilodilo

**Comment by Globarti** [comment]
The above concept covers both ideas from:
https://github.com/10clouds/aiconsole/issues/555
https://github.com/10clouds/aiconsole/issues/557

**Comment by cielecki** [comment]
Potential implementation of #433
