### ISSUE TITLE
Style modal when leaving the project

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#568]
**Modal when leaving the project is not styled, it should use our default style.**
![image](https://github.com/10clouds/aiconsole/assets/152965457/e4946225-ad7b-48b9-8e5d-bc1309ae8a54)

**Comment by jakubbilko** [comment]
Points 1 & 2 were also covered by #571

**Comment by kilodilo** [comment]
This ticket may not be relevant anymore, I don't have such message in the newest released version when leaving the project.

**Comment by aga-gasinska** [comment]
<img width="1262" alt="Zrzut ekranu 2024-01-24 o 11 59 07" src="https://github.com/10clouds/aiconsole/assets/155951278/89b863c9-7652-49e1-8b00-4faddd0c27e6">
