### ISSUE TITLE
Design frontend fixes to the prereleased version (assets part)

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#570]
1. **Chat options in sidebar adjustments**
1.1. Wrong alignment of the text and icon:
Text should be centered with the icon, now it looks like the text is aligned more to the bottom
![image](https://github.com/10clouds/aiconsole/assets/152965457/95669e22-feab-4d50-957e-36234fdced79)
1.2. The "AI Choice" is not a placeholder text, it's a default choose and should use test style "p" (paragraph), not bold one as now.
![image](https://github.com/10clouds/aiconsole/assets/152965457/d06c0eb2-1e5d-429c-b3fa-b2f582553de3)

2. **System material/agent settings - Wrong alignment of the text in the communicate in the top:**
Now it looks like the text is closer to the bottom but it should have equal space from the top and the bottom.
2.1. **There is also an incorrect sentence "This is a system agent start editing to overwrite it."** 
It should be "This is a system agent. Start editing to overwrite it."
![image](https://github.com/10clouds/aiconsole/assets/152965457/7fe6a6d2-1bfb-401b-925e-d90ce6988aaa)

3. Agent settings - The elements in the dropdown list shouldn't have Bold style.
It should be Regular, check it in the design system elements (here https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=357%3A4709&mode=design&t=kjxfwLVScgPn4Ylq-1). 
Bold should be used only for the placeholder text "Choose execution modes"
![image](https://github.com/10clouds/aiconsole/assets/152965457/7926a807-992b-4b81-bf76-9288a885eae9)

4. **Agent and Material settings - Text area (with system prompt or with the text) uses text style with wrong line height - too small.**
It is horrible to read, please use normal paragraph style which we have in design system :)
If we want to have smaller line height for the code areas than we can add additional text style specifically for code with the smaller line height.
![image](https://github.com/10clouds/aiconsole/assets/152965457/4b0f4b87-0e25-447a-99e3-57eec2efa97c)

5. **Material settings - Preview mode toggle uses wrong styling**
Right now it has very light gray outline, in the design you can check that light outline is only on hover, normally it should be Gray 500 color. (here https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=375%3A3951&mode=design&t=kjxfwLVScgPn4Ylq-1)
![image](https://github.com/10clouds/aiconsole/assets/152965457/4b147440-de4a-4f18-bfdc-ddce12c79f47)

6. **Add new material - please change the color of the text label "Materials:" to the lighter, current one is not easy to read.**
It was my fail earlier, I changed it to: Gray 400. The test style should also be "p" (paragraph), please check if it is so.
![image](https://github.com/10clouds/aiconsole/assets/152965457/bb8195bb-7c08-425a-8c07-0b8dc191a089)

**Comment by kilodilo** [comment]
Ok, I moved also the first point to this task :) so all of them are on you ;)

**Comment by aga-gasinska** [comment]
@kilodilo please review this task and if everything is fine close it ;)

**Comment by jakubbilko** [comment]
Unfortunately I can't see the second issue on my display (Retina). I pushed a fix that might solve it, but I need to ask @pwksn to check on his display.
