### ISSUE TITLE
Uncaught (in promise) Error: Chat is not initialized

### ISSUE THREAD

**Issue by kgradzka** [10clouds/aiconsole#573]
## Steps to Reproduce the Problem
1. Create new chat and click "Guide me".
2. Try to create another chat while agent is still generating response. 
3. "Are you sure you want to exit this chat?" modal pops up, click "Save" -> errors are visible.

## Specifications
- Platform: Win10
![chat_not_initialized](https://github.com/10clouds/aiconsole/assets/61430006/ad97cdea-1b2f-4126-9fd1-ace20cce8d36)
![chat_not_initialized_2](https://github.com/10clouds/aiconsole/assets/61430006/046384f7-8ef2-4407-a254-ab72407a5d71)

**Comment by udislau** [comment]
Duplicate
