### ISSUE TITLE
Change typography width for the chat test styles

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#574]
These headers used now had black or extrabold width, they are hardly readable in this width so I wanted to make a change to all chat heading styles to:
font-weight: 700;

![image](https://github.com/10clouds/aiconsole/assets/152965457/4432021b-09ba-4c41-b075-2da75caf9573)
https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=1743%3A4559&mode=design&t=Ic7fvmBPVZdVtJnB-1

**Comment by aga-gasinska** [comment]
@kilodilo could you please recheck it and if fine close the task

**Comment by kilodilo** [comment]
Hm, I feel it is still hardly readable.
It is how it looks now:
![image](https://github.com/10clouds/aiconsole/assets/152965457/6fd062cf-34cf-40f6-ade9-23b1cb39cb55)

and this is how it looks like in the design 
![image](https://github.com/10clouds/aiconsole/assets/152965457/74fc9dc6-88d5-4a8b-be3d-d46cf2c0f851)

@AGasior

**Comment by AGasior** [comment]
Now it should be correct
![Zrzut ekranu 2024-01-25 o 08 54 21](https://github.com/10clouds/aiconsole/assets/102804214/ef525723-bcb8-4f77-b21d-d6d8ef4bc947)
![Zrzut ekranu 2024-01-25 o 08 52 48](https://github.com/10clouds/aiconsole/assets/102804214/d1a452d0-e7f8-457e-8aab-d3ea58dc63ca)
95b6288b3a)
![Zrzut ekranu 2024-01-25 o 08 52 54](https://github.com/10clouds/aiconsole/assets/102804214/a7f876ec-a4f9-4046-a3ef-e115cc28b9fe)
![Zrzut ekranu 2024-01-25 o 08 53 01](https://github.com/10clouds/aiconsole/assets/102804214/ebed4c1c-735f-45c0-a626-e18adbba882e)

**Comment by aga-gasinska** [comment]
@kilodilo could you please verify that?

**Comment by kilodilo** [comment]
yes, this is good now :)
