### ISSUE TITLE
Add "Analysis process" checkbox to Chat options

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#577]
We need to add a checkbox in Chat option which turn on and off "AI Analysis process".
Checkbox for materials should be moved up, as it is in the design.
![image](https://github.com/10clouds/aiconsole/assets/152965457/dd11e6d2-f984-41ba-8c1f-86dd0f6a2751)

https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=2868%3A13873&mode=design&t=sYQN5C8KAaarWcex-1

**Comment by jakubbilko** [comment]
Not relevant anymore as per our discussion on daily.
