### ISSUE TITLE
Errors after editing agent's message in the chat

### ISSUE THREAD

**Issue by kgradzka** [10clouds/aiconsole#580]
## Expected Behavior
User should be able to edit agent's message without causing errors.
## Actual Behavior
After editing agent's message and clicking "Save" button errors are visible in console but message is edited and saved. Errors are not visible after editing user's message.
## Steps to Reproduce the Problem
1. Open chat.
2. Edit agent's message.
3. Click "Save" button.

## Specifications
- Platform: Win10
![logging_error](https://github.com/10clouds/aiconsole/assets/61430006/ca693f82-9a81-42d5-9577-5f0acdc6f1f0)
![logging_error_editing_agents_message](https://github.com/10clouds/aiconsole/assets/61430006/a80aef76-e0b9-4984-976d-8425d995b22d)
![logging_error_editing_agents_message_2](https://github.com/10clouds/aiconsole/assets/61430006/6ef227a7-5d69-41e2-a4ef-74fb9a1af4ba)

**Comment by pbaranski9411** [comment]
It's problem only on windows. On Mac everything is working properly.

@aga-gasinska probably we need to have Windows instance to test it out

**Comment by pbaranski9411** [comment]
@udislau could you check it on windows?

**Comment by udislau** [comment]
Fixed
