### ISSUE TITLE
Pop-up with "Saved" information needs to be improved

### ISSUE THREAD

**Issue by kgradzka** [10clouds/aiconsole#583]
## Actual Behavior
After editing material user sees popup with only "Saved saved" text.
## Steps to Reproduce the Problem

1. Edit some material, for example note.

![saved_popup](https://github.com/10clouds/aiconsole/assets/61430006/ae17f708-c948-48d8-8bf2-647b9e81a031)

**Comment by kilodilo** [comment]
The problem occur after editing every material.

I've listed some positive and negative text templates.
Do we have more states that needs copy? Let me know :)

https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=3231%3A15634&mode=design&t=n9nvuAeSpnMmME3D-1

I'm moving this to the frontend team :)

**Comment by kgradzka** [comment]
Retested on: 0.2.10-rc.1 on Win10. 

Copy on popup was changed. ✔️ 
![retest_issue_583](https://github.com/10clouds/aiconsole/assets/61430006/2272964e-b6e4-47ed-b50a-d3f753d832b9)
![retest_issue_583_2](https://github.com/10clouds/aiconsole/assets/61430006/07ba5c70-ded0-4302-b802-27bcd6320012)
