### ISSUE TITLE
The avatars are not loading properly

### ISSUE THREAD

**Issue by udislau** [10clouds/aiconsole#585]
It must instantly show correct avatar picture

https://github.com/10clouds/aiconsole/assets/30052145/19c83747-b5e2-486f-9ff1-1fd600aa19d4

**Comment by cielecki** [comment]
Something similar happens when I click "?"

**Comment by cielecki** [comment]
Also this:

![image](https://github.com/10clouds/aiconsole/assets/101296/7cd876cb-0554-4218-a440-668d691aacb0)

**Comment by cielecki** [comment]
This probably should be fixed after this one: https://github.com/10clouds/aiconsole/issues/586

**Comment by jakubbilko** [comment]
So from what I noticed, the change in the agent avatar is because when analysis is running, the avatar component gets `director` passed as the value (the blue avatar) and later it switches to the proper agent avatar.

**Comment by kilodilo** [comment]
Let's use this  avatar when analysis is running https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=3627%3A23539&mode=design&t=PCnu4BNmL0niGGxI-1

**Comment by AGasior** [comment]
Now user avatar is immediately displaying which user set on settings ,  avatar which @kilodilo prepared  is displaying during analyzing and if agent is chose changed to avatar of agent.

https://github.com/10clouds/aiconsole/assets/102804214/2432b205-b2ba-4ac2-98c6-e8fde2509a2a

**Comment by kilodilo** [comment]
That's great. But we should also think about the reloading image system - right now we have some ugly blinking text inside 
![image](https://github.com/10clouds/aiconsole/assets/152965457/c9914931-c703-47f4-945a-9d7c497ce8eb)
What can we do with it?

Can I ask you also how it looks now with the user icon? What is the default icon for the user? Shouldn't we implement one for the user also?

**Comment by AGasior** [comment]
We have 19 images which are randomly assign as avatar. Correct me @udislau if I am wrong.

for example:
![1](https://github.com/10clouds/aiconsole/assets/102804214/09f1be3a-94a9-4e60-be85-a288ee18eecf)
![2](https://github.com/10clouds/aiconsole/assets/102804214/b0ee4ab9-44a5-4779-8087-71ecb3fa04a6)
![3](https://github.com/10clouds/aiconsole/assets/102804214/f13e288e-2594-48c2-85c2-8398aa2b3728)

**Comment by AGasior** [comment]
@kilodilo I fix blinking text, now it shouldn't be visible during generating message.

**Comment by kilodilo** [comment]
Great info regarding this blinking text.
I'm not sure about this user avatar pack. Let me prepare a package which will look better on dark screens. The one you use now are better for light-mode apps.
I'm adding an issue for these avatars and will assign to you @AGasior when they will be ready

**Comment by aga-gasinska** [comment]
@kilodilo please link the issue here when you add it and then close this one. ;)

I checked and I don't see the blinking text now.

**Comment by kilodilo** [comment]
This is the task on me related to user avatars -> https://github.com/10clouds/aiconsole/issues/686
I can't check the current one change so if @AGasior can share his screen record then we can close this issue :)

**Comment by AGasior** [comment]
here is screen record

https://github.com/10clouds/aiconsole/assets/102804214/0c9219eb-1d61-4067-9a00-1fe1df836f8d

**Comment by kilodilo** [comment]
ok avatar loads fine now :) I'll add another issue regarding the background loading because it is something that is very "hard" and blinking
