### ISSUE TITLE
Issues with the current settings screen

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#587]
![image](https://github.com/10clouds/aiconsole/assets/101296/7141e134-55c9-4420-8e6c-f586050848c5)

"Hello, <pencil>" when I have no name set is not a good UX, in general I'm on the fence with this "Hello, name" in the setting screen.

API - this is not descriptive at all of what this section is about

Code run - Always run code - why two labels for the same thing?

**Comment by udislau** [comment]
Settings, after merge #521, will always display `user` if username is absent.

<img width="450" alt="Screenshot 2024-01-13 at 11 31 52" src="https://github.com/10clouds/aiconsole/assets/30052145/f633e31d-d718-40dd-a790-799216dc1383">

**Comment by kilodilo** [comment]
We can change these labels to these:
![image](https://github.com/10clouds/aiconsole/assets/152965457/043ddd4c-abb8-4e48-b587-f400057d6be9)

Are you ok with this @cielecki ?

**Comment by cielecki** [comment]
I'm good both with and without the description

**Comment by cielecki** [comment]
All changes are nice,

How about the Hello, xxx?

**Comment by kilodilo** [comment]
![Console settings](https://github.com/10clouds/aiconsole/assets/152965457/f9dbb51d-2705-4b29-aad7-82bf08bfc00a)

I checked if there are some other apps showing hello to the user in the settings and it's not that popular so ok, let's get rid of this.
I thought about adding a box around user settings - discord has this kind of solution.
I think if we want to show the description to the "Open API key" than we should also add it to the "Always run code".
I've implemented these changes. check it pls @cielecki

**Comment by cielecki** [comment]
Looks good

**Comment by kilodilo** [comment]
I asked Chris for help with the description and I changed it slightly in the design.
We can implement changes as it is in the design here: https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=3343%3A14652&mode=design&t=MDpjRC0SeES3l3Um-1
