### ISSUE TITLE
Issue with list formatting

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#588]
![image](https://github.com/10clouds/aiconsole/assets/101296/ede5dbc4-fda6-4595-8cb3-522735cf3c0a)

**Comment by AGasior** [comment]
list is displaying properly

![Zrzut ekranu 2024-01-15 o 17 31 33](https://github.com/10clouds/aiconsole/assets/102804214/5409c9c6-ca96-48ef-83a9-79ab879e41d6)

**Comment by jakubbilko** [comment]
Also seems to be working fine for me

**Comment by kgradzka** [comment]
Retested on: 0.2.10-rc.1 on Win10.

List formatting is now correct. ✔️ 
![retest_issue_588](https://github.com/10clouds/aiconsole/assets/61430006/948c8465-3b11-40ef-b500-70de28c91995)
![retest_issue_588_2](https://github.com/10clouds/aiconsole/assets/61430006/3fb9563a-b300-42d8-833d-8aa0e2f014f1)
