### ISSUE TITLE
Chats are no longer properly named

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#589]
![image](https://github.com/10clouds/aiconsole/assets/101296/411bbbb6-3ad1-453c-9c1c-702268a8fc3e)

**Comment by udislau** [comment]
The issue with 'New Chat' ✅ has been resolved, and the code looks good 👍.

However, a new issue has arisen, which is not directly related to the previous one: it is not possible to change the chat name via the interface ❌.
