### ISSUE TITLE
Import chat from ChatGPT link

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#591]

**Comment by kilodilo** [comment]
Add an input to conversation to paste the link to ChatGPT conv

**Comment by kilodilo** [comment]
We should put this on the welcome screen. Here is the design:
https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=3658%3A19475&mode=design&t=PCnu4BNmL0niGGxI-1

**Comment by cielecki** [comment]
This should not be on the welcome screen of a given chat, it's a minor feature

**Comment by kilodilo** [comment]
If it is the action that the user needs to take before starting the conversation than maybe we should add it to dropdown liske below "new chat" - can user import only ChatGPT conversation or maybe he can add more? 
![image](https://github.com/10clouds/aiconsole/assets/152965457/bcb3dbc8-071b-4c0b-8484-24fc03cd5640)

**Comment by cielecki** [comment]
Now I'm starting to think that this is so specific, that this should just be a material, and as such it may not have any interface ... but maybe we should allow in some way for materials to define interfaces? or add buttons to the UI? this is probably more for GenUI part of things ...

**Comment by cielecki** [comment]
Implemented in https://github.com/10clouds/aiconsole/commit/f50a7cf1eebd08c8912c748c94f30b70060bfd46

**Comment by cielecki** [comment]
https://github.com/10clouds/aiconsole/assets/101296/19c8d07b-e805-4dc4-a2d8-34fde7ceb3a5
