### ISSUE TITLE
After merge the settings format has changed and is not backwards compatibile

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#592]
Old format:

[settings]
openai_api_key = "sk-..."
code_autorun = false

New format:

openai_api_key = "sk-..."
code_autorun = true

**(Note from the future: this is fixed now)**

**Comment by cielecki** [comment]
Furthermore, gpt_modes are empty when loaded

**Comment by cielecki** [comment]
I will fix this because I can not work on other stuff

**Comment by cielecki** [comment]
One more bug (minor one): the settings were not cached and were read from the fs each time they were accessed

**Comment by cielecki** [comment]
Furthermore, some settings were saved to global settings file and some to local settings file, for example enabled / disabled status was saved locally. This was not preserved.

**Comment by cielecki** [comment]
GPT modes do not work right now

**Comment by cielecki** [comment]
I have made initial refactorings but some of those things still do not work

**Comment by pbaranski9411** [comment]
@cielecki looks good to me and @udislau. Moving it to the qa

**Comment by aga-gasinska** [comment]
@udislau could you please recheck it and if it's fine close this task
