### ISSUE TITLE
Share small stuff from AIConsole for social media and vitality (Brag button)

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#604]

**Comment by Globarti** [comment]
The Idea is to have a button inside the app that allows to easily share the work done by user in AIConsole to the web. 
BRAG BUTTON -> **Means giving opportunity to a user to BRAG about his achievement inside AI-CONSOLE.** 

It could work different ways depending on the development stage of AIConsole. 

EASY to introduce:
Save the conversation in a txt form or a good looking PDF to share

PERFECT in terms of sharing quality:
Generate link with conversation, thumbnail and chat settings detail so people who will see this could start chatting from the go. It could work as a "publish" on Notion, allowing users to start from the shared spot of a conversation. 


HOW GPT IS DOING IT:
<img width="1438" alt="image" src="https://github.com/10clouds/aiconsole/assets/1726746/0f8b1da0-268a-44c6-bcf1-ecf4b90c5b48">

AND THE LINK:
https://chat.openai.com/share/03b033ac-3a16-458c-8af5-2d2a336a576a

HOW OTHERS DO IT:
<img width="930" alt="image" src="https://github.com/10clouds/aiconsole/assets/1726746/2a35553e-d125-49f5-bd1f-2ad9bbf6228b">


@kilodilo

**Comment by cielecki** [comment]
Solved by anyone with link access level in #716
