### ISSUE TITLE
Issue with opening AIConsole locally on Win10

### ISSUE THREAD

**Issue by kgradzka** [10clouds/aiconsole#616]
## Actual Behavior
AIConsole is not starting after trying to open it locally on Win10.

## Specifications
- Platform: Win10
![aiconsole_win10](https://github.com/10clouds/aiconsole/assets/61430006/32744364-8ecb-4291-93a9-21b977ac55d9)

**Comment by udislau** [comment]
Resolved! Fixed with https://github.com/10clouds/aiconsole/commit/9c90fd688c746aab4536e4d9879324094b3cf438
