### ISSUE TITLE
New chat doesn't show up in the sidebar + it has always the name "New chat"

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#618]
Hey, in the newest version every new chat I start doesn't show in the left sidebar when started, prev:
![image](https://github.com/10clouds/aiconsole/assets/152965457/8eb6eb79-5722-4d59-870d-e3fcad17623a)

When I go out of the project and go back to it than I can finally see the chat in the sidebar but the chat name should use first sentence from the chat, not "New chat" text like here:
![image](https://github.com/10clouds/aiconsole/assets/152965457/392f72d8-eb57-4cca-a1a4-694e20959f1e)

**Comment by kgradzka** [comment]
Retested on 0.2.10-rc.1 on Win10.
Bug still exists. After opening project and creating new chat, prompting it with anything, chat name is not visible on the list. It doesn't appear on the list after closing and opening AIConsole.

https://github.com/10clouds/aiconsole/assets/61430006/dfffa5f0-1162-4a27-a1c1-8c68cf75070c

**Comment by kgradzka** [comment]
Retested on newest changes on /main on Win10.

Bug no longer occurs but new chat's name is visible only after creating another chat. Should it work like that? @AGasior 

https://github.com/10clouds/aiconsole/assets/61430006/76983085-4b94-47ec-aa71-cf1613ed9710

**Comment by AGasior** [comment]
I added handling when user use "Guide me" button

**Comment by kgradzka** [comment]
Retested on: [v0.2.10-rc.6](https://github.com/10clouds/aiconsole/releases/tag/v0.2.10-rc.6) on Win10.

Fixed. ✔️
