### ISSUE TITLE
Issue with transisitons while changing chats 

### ISSUE THREAD

**Issue by aga-gasinska** [10clouds/aiconsole#621]
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by cielecki** [comment]
On the frontend side I noticed that we have multiple issues with transitions on the frontend:
When you click a project, and it takes a while - nothing happens on the backend
When switching chats I constantly get the rolling cog for like 0,2 secs and the left side panel flickers
Vlad do you see  mypy errors in the code? I started seeing a lot of them today.

**Comment by cielecki** [comment]
If the backend is slow: I get the enter openai key and then I get the recent projects
