### ISSUE TITLE
500 error on /api/projects/recent after opening AIConsole locally

### ISSUE THREAD

**Issue by kgradzka** [10clouds/aiconsole#622]
The same errors were visible in local console and in Console tab in AIConsole.

500 error is visible in AIConsole after opening it. Recent projects are not visible at the first screen. 

## Specifications
- Platform: Win10

![500_error_recent_projects](https://github.com/10clouds/aiconsole/assets/61430006/680b7738-a9f2-4683-8814-63513b231a1b)
[errors.txt](https://github.com/10clouds/aiconsole/files/13950654/errors.txt)

**Comment by aga-gasinska** [comment]
@kgradzka please check with the latest release if this still happen

**Comment by kgradzka** [comment]
Retested on [v0.2.10-rc.6](https://github.com/10clouds/aiconsole/releases/tag/v0.2.10-rc.6) on Win10.

Bug no longer occurs. ✔️
