### ISSUE TITLE
Problems with the main screen

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#626]
<img width="818" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/d1437709-64d9-433b-b9d0-d682b33d159e">

- Different heights of boxes
- Scroll bar scrolls only the boxes

**Comment by kgradzka** [comment]
Blocked by https://github.com/10clouds/aiconsole/issues/637. Is it possible that this is related @AGasior?

**Comment by AGasior** [comment]
No it is not related.

**Comment by kgradzka** [comment]
Retested on the [v0.2.10-rc.6](https://github.com/10clouds/aiconsole/releases/tag/v0.2.10-rc.6) on Win10. 

Fixed. ✔️ 
![retest_issue_626](https://github.com/10clouds/aiconsole/assets/61430006/0a0c0841-6c11-4edc-89fe-c6e0d06ee408)
