### ISSUE TITLE
Agents system prompt descriptions are not coherent 

### ISSUE THREAD

**Issue by aga-gasinska** [10clouds/aiconsole#627]
Assistant, Automator, Critic and Planner descriptions do not have breaks between lines. Programmer and Writer have a line break between each sentence.
<img width="913" alt="Zrzut ekranu 2024-01-17 o 08 16 52" src="https://github.com/10clouds/aiconsole/assets/155951278/3e31c661-07d0-4f59-8eb1-b0c2bafe3fc7">

<img width="913" alt="Zrzut ekranu 2024-01-17 o 08 17 26" src="https://github.com/10clouds/aiconsole/assets/155951278/e83f7b23-abff-46ec-964a-6c267fbcb02f">

@kilodilo which version is correct?

**Comment by AGasior** [comment]
I added lines between the sentences

**Comment by kilodilo** [comment]
I'm not sure if it is ok. This is the point 4. in my list of frontend fixes - including bigger line-height.
Is it fixed or there are additional breaks between the lines? https://github.com/10clouds/aiconsole/issues/570
