### ISSUE TITLE
Line to be removed from a confirmation modal 

### ISSUE THREAD

**Issue by aga-gasinska** [10clouds/aiconsole#628]
<img width="472" alt="Zrzut ekranu 2024-01-17 o 08 40 32" src="https://github.com/10clouds/aiconsole/assets/155951278/2c4cb6c9-c50c-4f3f-b7d9-ea2ef84c8ba8">

There should be no line on the confirmation modal.

**Comment by kgradzka** [comment]
Retested on the newest changes on Win10.
Line is no longer visible. ✔️ 
![retest_issue_628](https://github.com/10clouds/aiconsole/assets/61430006/38701f74-44ca-49d5-ad98-249d44f34740)
