### ISSUE TITLE
Issues with code outputs: RuntimeError: No venv located

### ISSUE THREAD

**Issue by kgradzka** [10clouds/aiconsole#636]
## Actual Behavior
Appropriate output is missing from agent. Stop generation button doesn't work.

Traceback (most recent call last):
  File "C:\Users\klaudiagradzka\Downloads\AIConsole-win32-x64-0.2.10-rc.1\resources\python\Lib\site-packages\aiconsole\core\code_running\code_interpreters\subprocess_code_interpreter.py", line 118, in run
    await self.wait_for_path()
  File "C:\Users\klaudiagradzka\Downloads\AIConsole-win32-x64-0.2.10-rc.1\resources\python\Lib\site-packages\aiconsole\core\code_running\code_interpreters\subprocess_code_interpreter.py", line 227, in wait_for_path
    raise RuntimeError(f"No venv located at {venv_path} after {timeout} seconds")
RuntimeError: No venv located at C:\Users\klaudiagradzka\Documents\AI draft test\.aic\venv\aic_version after 100 seconds

## Steps to Reproduce the Problem
1. Prompt console with "calculate factorial of x".
2. Prompt console with image generation. 

## Specifications
- Version: 0.2.10-rc.1 as well as main with newest changes
- Platform: Win10
![calculate_factorial_missing_output](https://github.com/10clouds/aiconsole/assets/61430006/c43f3a63-2a23-42ca-864b-f68f82e7b59d)
![image_generation_output](https://github.com/10clouds/aiconsole/assets/61430006/1e8215b3-3b67-4304-8f9d-ca01ca2f03a8)

https://github.com/10clouds/aiconsole/assets/61430006/521646d6-c0a0-4083-803e-8f28c604513b

https://github.com/10clouds/aiconsole/assets/61430006/8b4e7faf-f112-4ea7-bee3-f13ec75964d9

**Comment by udislau** [comment]
Fixed in https://github.com/10clouds/aiconsole/commit/a1443b440b15a910d40549063f8e5d33335c5c99

**Comment by kgradzka** [comment]
Retested on [v0.2.10-rc.6](https://github.com/10clouds/aiconsole/releases/tag/v0.2.10-rc.6) on WIn10.

Bug no longer occurs, outputs are visible. ✔️ 
![retest_issue_636_1](https://github.com/10clouds/aiconsole/assets/61430006/b636a047-fdc6-4ebc-98a5-abec80fa3c63)
![retest_issue_636_2](https://github.com/10clouds/aiconsole/assets/61430006/cf6b4a41-7a87-482c-a8f3-a3fedde3a801)
