### ISSUE TITLE
500 Internal Server Error on /api/projects/close

### ISSUE THREAD

**Issue by kgradzka** [10clouds/aiconsole#637]
## Actual Behavior
500 error is visible after clicking on AIConsole logo in upper left, next to the project name field.

## Steps to Reproduce the Problem
1.Click on the AI Console logo.

## Specifications
- Version: 0.2.10-rc.1 and /main with newest changes
- Platform: Win10

https://github.com/10clouds/aiconsole/assets/61430006/aa36115b-8a34-445b-aa27-d17bfdaf5490

**Comment by jakubbilko** [comment]
I don't have this problem on my mac, might be a Windows issue.

**Comment by udislau** [comment]
Works fine on Windows, recheck

**Comment by kgradzka** [comment]
Retested on [v0.2.10-rc.6](https://github.com/10clouds/aiconsole/releases/tag/v0.2.10-rc.6) on WIn10. 

Bug no longer occurs. ✔️ 

https://github.com/10clouds/aiconsole/assets/61430006/aa8b9c28-0230-4472-a8ea-bbd3a849797d
