### ISSUE TITLE
Uncaught (in promise) Error: Chat is not initialized - error visible while trying to create new chat

### ISSUE THREAD

**Issue by kgradzka** [10clouds/aiconsole#639]
## Steps to Reproduce the Problem
1. Create new chat.
1. Prompt chat with anything.
1. Try to create another chat. 

## Specifications
- Version: 0.2.10-rc.1
- Platform: Win10

https://github.com/10clouds/aiconsole/assets/61430006/a8a4715f-ce47-4acb-90c5-8debe2eb114d

**Comment by arudzinska** [comment]
Confirmed that on my Ubuntu 22.04.3 LTS and there is **no such error** when opening the 2nd (and further) chat(s).

**Comment by jakubbilko** [comment]
Tested on MacOS 12.6 (dev and prod ver) - also no issue.

**Comment by udislau** [comment]
No luck replicating issue on windows
