### ISSUE TITLE
Component updating error

### ISSUE THREAD

**Issue by jakubbilko** [10clouds/aiconsole#648]
## Expected Behavior

There should be no error thrown.

## Actual Behavior

![Screen Shot 2024-01-19 at 11 59 11 AM](https://github.com/10clouds/aiconsole/assets/908399/81e1bcd8-a200-46f7-a46e-cd2cbe6ef7c5)

## Steps to Reproduce the Problem

1. Open the app
2. Submit a message or use the Guide Me button
3. This bug only happens once during the first chat interaction

## Specifications

- Version: Latest code from `main`
- Platform: macOS 12.6

**Comment by aga-gasinska** [comment]
I've check it with "guide me button" and there was no error.
