### ISSUE TITLE
Errors after creating new chat 

### ISSUE THREAD

**Issue by kgradzka** [10clouds/aiconsole#655]
## Actual Behavior
Every time new chat is created "Logging error" and traceback is visible. Then sometimes after prompting agent traceback is also visible (hard to reproduce this second scenario).

One scenario:
1. Create new chat. -> traceback visible
2. Use "Guide me" option.
3. Change chat to another one without stopping output generation in the first one. -> traceback visible
4. Go back to the first chat. -> empty chat is visible, without prompt from user

## Specifications
- Version: [v0.2.10-rc.6](https://github.com/10clouds/aiconsole/releases/tag/v0.2.10-rc.6)
- Platform: Win10
![prompt_errors](https://github.com/10clouds/aiconsole/assets/61430006/0edb1369-f5b4-45d5-9118-d13793ab7cee)
![prompt_errors_2](https://github.com/10clouds/aiconsole/assets/61430006/1c3d7d8f-af89-404c-8192-3e524dffbbd1)
![prompt_errors_3](https://github.com/10clouds/aiconsole/assets/61430006/948fb0d0-9992-4c0d-a387-f754f766bfb5)

https://github.com/10clouds/aiconsole/assets/61430006/17ca985a-6505-45b7-81aa-0756c3525097
https://github.com/10clouds/aiconsole/assets/61430006/b7158482-39a4-425a-96e6-75b3879956b9

**Comment by aga-gasinska** [comment]
this is development issue not related to the release - logging error (not critical)
