### ISSUE TITLE
Remove zip files from the release assets

### ISSUE THREAD

**Issue by aga-gasinska** [10clouds/aiconsole#656]
## WHY?
@udislau during debugging AIConsole on windows noticed that path to ['user_data_dir'](https://platformdirs.readthedocs.io/en/latest/api.html#user-data-directory) is different for AIConsole installed via _exe_ and _zip_

<img width="800" alt="Zrzut ekranu 2024-01-19 o 11 36 38" src="https://github.com/10clouds/aiconsole/assets/155951278/4c9e69c9-2f9e-4e7d-93cd-9126cc779c80">

**Comment by aga-gasinska** [comment]
We need to bring back zip files as they are related with auto-upgrade

**Comment by udislau** [comment]
On Windows 10 auto-update is still present
