### ISSUE TITLE
Generate with AI function in Avatar change doesn't work

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#658]
Hey, if this solution doesn't work now we should not show it:
![image](https://github.com/10clouds/aiconsole/assets/152965457/5e4aab14-eec7-44cf-86b0-fd1bf90a099f)

Steps to Reproduce the Problem
1.Open on Win
2.Go to agent settings
3. Use right click mouse and you will see the menu

### Specifications
Version: Version 0.2.10
Platform: Windows11

**Comment by udislau** [comment]
Issue #251 is planned for release 0.3.X. The frontend code has been merged into the main branch, as seen here: [ImageUploader.tsx Code Reference](https://github.com/10clouds/aiconsole/blob/f96492e3e9324f0d4208b8badfbddf17f16e9cdf/frontend/src/components/common/ImageUploader.tsx#L76-L82). However, **there is currently no backend implementation to support it**.

From this update, we have two key action items:
- We need to establish clear guidelines for how we approach releases, particularly with regards to feature development.
- During my testing on both MacOS and Windows, the options menu associated with this feature did not display. This needs to be investigated and resolved.

Additionally, @jakubbilko is planning to overhaul the settings structure soon.

**Comment by aga-gasinska** [comment]
I've just check on the latest version and I also cannot see this option in the console (which is good as it shouldn't be displayed until we have backend).

**Comment by kilodilo** [comment]
Hey, yes, it happens on the newest released version. I've added specificaiton to the task description. Im using Win11

**Comment by aga-gasinska** [comment]
@udislau any idea why it's hidden on Mac but visible on Windows?

**Comment by udislau** [comment]
There are 2 key points regarding this issue:

- Issue #251 is scheduled for inclusion in release 0.3.X. It should be temporarily disabled (commented out) until the back-end is fully prepared to support it.
- There is a 🐞 bug in the current front-end implementation of issue #251 — the options menu fails to display when right-clicking.

➡️ @jakubbilko will be tasked with resolving these issues.

**Comment by aga-gasinska** [comment]
checked on MacOS and this hidden. @kilodilo please check if it's also hidden on Windows

**Comment by kilodilo** [comment]
Yes, AI generation is hidden :)
