### ISSUE TITLE
Saving of an avatar doesn't work

### ISSUE THREAD

**Issue by aga-gasinska** [10clouds/aiconsole#665]
Saving option doesn't work when you want to save the avatar you chose.
 
Please see the movie uploaded for the path I followed. 

https://github.com/10clouds/aiconsole/assets/155951278/390d9ef1-0cbb-4c0d-ac7a-4585eb658b39

It happend on MacOs

**Comment by AGasior** [comment]
I checked it on MacOs

https://github.com/10clouds/aiconsole/assets/102804214/925bae92-0205-4ebc-9be4-91fe40bd7688

**Comment by aga-gasinska** [comment]
I'm closing it as it's a duplicate and the problem was already mentioned in #349
