### ISSUE TITLE
🐞 Generating listed links elements is buggy and the links don't work

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#666]
![image](https://github.com/10clouds/aiconsole/assets/152965457/c95b0799-ea56-4a0f-bd6b-40e4ac4ad93a)
Hey, I've found the bug that when the message is being generated the listed links shows very strange, after the full line load then it changes to the link and looks good. Can we hide the generation of the links?

### Steps to Reproduce the Problem
1.Open on Win
2.Open the project and start new chat
3. Write "hello" in the chat and send.
4. Wait for the answer

### Specifications
Version: Version 0.2.10
Platform: Windows11

**Comment by kilodilo** [comment]
I also found out that by clicking on the listed links - none of them works 
![image](https://github.com/10clouds/aiconsole/assets/152965457/922170f0-dfe6-436d-80a8-33e0943f4142)

is it happening only in my version?

**Comment by jakubbilko** [comment]
So the links are streamed as markdown text, we can't really know when something is a link until it arrives fully and is formatted by our component.

What version of the app is this? What OS? Pls use the issue template :)

**Comment by kilodilo** [comment]
It happens on Win11, I use the 0.2.10 version.
Btw where's the issue template? :)

**Comment by firuzaharun** [comment]
Works for me properly, closing the task
