### ISSUE TITLE
🐞 Overwriting the agent is not possible

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#667]
### The Problem
![image](https://github.com/10clouds/aiconsole/assets/152965457/b5969d16-21e8-43ba-8e7d-cff0b0537468)
Even though I know I'm overwriting the agent - I can't do this - check the system info box. Why is it like that? I should have the possibility to overwrite it.

### Steps to Reproduce the Problem
1.Open on Win
2.Go to system agent settings
3. Change the avatar
4. Click "Overwrite"
5. You get the notification that it can't be saved

### Specifications
Version: Version 0.2.10
Platform: Windows11

**Comment by jakubbilko** [comment]
@aga-gasinska why is this assigned to frontend? Was there any new discussion on how to solve this? The current error comes from the backend validation. Let's discuss.
