### ISSUE TITLE
Chat's content disappears when you switch chats and then come back

### ISSUE THREAD

**Issue by aga-gasinska** [10clouds/aiconsole#673]
## Actual Behavior
Chat was generating a reply to my task but in the meantime I changed the chat. When I came back the content of the chat was gone. The whole page was black. 
However, after I changed the chat again and came back to the original one the content loaded. 

## Steps to Reproduce the Problem

please see the video 
https://github.com/10clouds/aiconsole/assets/155951278/588051d1-14f7-42e4-a6f2-8c5167af8ce3

## Specifications

- Version: [v0.2.10]
- Platform: MacOS

**Comment by aga-gasinska** [comment]
we need to have a loader

**Comment by AGasior** [comment]
Now if user submit prompt change chat and then switch again to chat, where message is generating, user sees indicator until message is ready.

https://github.com/10clouds/aiconsole/assets/102804214/07d25d25-a400-4538-9ece-4fd31a31dae3

https://github.com/10clouds/aiconsole/assets/102804214/210eaf23-0f4e-4e0f-8591-9aa7830dd0b1

Now if user submit prompt and change chat and then switch again to chat, where message is generating, user sees indicator until message is ready.

**Comment by aga-gasinska** [comment]
Checked and the indicator appeared while the message was generating.
