### ISSUE TITLE
🐞 Chat settings are not visible

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#674]
### Problem
I can't see chat settings on my laptop. They are outside my screen I suppose, check this screenshot:
![image](https://github.com/10clouds/aiconsole/assets/152965457/e4713ea4-10f8-4a0f-923b-c8022608cb2c)

### Steps to Reproduce the Problem
1.Open on Win
2.Use standard laptop screen, 1920x1080px

### Specifications
Version: Version 0.2.10
Platform: Windows11

**Comment by pwksn** [comment]
The chat options are hidden intentionally, as the backend wasn't ready before the latest release. The options will be restored once the backend part is ready.
