### ISSUE TITLE
Styling improvement for the main screen

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#678]
1. In the main screen we see the rounded corners of the full viewport - we should get rid of these roundings - leave them as they are inside the project view 
![image](https://github.com/10clouds/aiconsole/assets/152965457/ff9cfbb0-ac76-4b89-900c-d70281c9f72a)
inside the project it is like that (and it should be the same at the main screen):
![image](https://github.com/10clouds/aiconsole/assets/152965457/999f63f0-7d54-46ba-9776-9f31cb63227e)

2. Secondary buttons like "Open an existing project" and "Setting icon" should not have filling color. Please, let's get rid of it :)
![image](https://github.com/10clouds/aiconsole/assets/152965457/a5c9ec6a-11f2-437e-8632-1cd20128022a)
this is how it is in the design: 
![image](https://github.com/10clouds/aiconsole/assets/152965457/dab1f233-d171-4e77-b86c-e3e7ed6a5e52)

**Comment by aga-gasinska** [comment]
Seems fine to me but @kilodilo could you please check as the person who opened the issue and if it's fine close it ;)

**Comment by kilodilo** [comment]
This is the new issue and I can't check if it is ok now. Maybe @AGasior you can share some screenshots so we can agree that it is ok now? :)

**Comment by AGasior** [comment]
@kilodilo 
![Zrzut ekranu 2024-01-25 o 12 59 37](https://github.com/10clouds/aiconsole/assets/102804214/a80b0dbc-062c-4812-82b7-d4c76648d5f5)

**Comment by kilodilo** [comment]
perfect, looking good now. thank you :)
