### ISSUE TITLE
Gradient to be removed

### ISSUE THREAD

**Issue by aga-gasinska** [10clouds/aiconsole#681]
## Expected Behavior
There shouldn't be no grey gradient on the tiles under the modal.
## Actual Behavior
<img width="1262" alt="Zrzut ekranu 2024-01-24 o 10 07 18" src="https://github.com/10clouds/aiconsole/assets/155951278/394a4521-d8ac-4551-873b-310d1a4e3c92">

## Steps to Reproduce the Problem

1. Open an existing project
2. Select an empty folder

## Specifications

- Version: 0.2.10
- Platform: MacOS

**Comment by aga-gasinska** [comment]
cc @kilodilo

**Comment by aga-gasinska** [comment]
<img width="1062" alt="Zrzut ekranu 2024-01-30 o 12 18 07" src="https://github.com/10clouds/aiconsole/assets/155951278/7541f231-1887-4baf-8a95-642e0f095af5">

I can still see the gradient on [v0.2.11-rc.3] on Mac

**Comment by AGasior** [comment]
@aga-gasinska Are you sure, you are checking newest version? Changes are on main branch.

**Comment by aga-gasinska** [comment]
Looks good now
