### ISSUE TITLE
🐞 Assets errors

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#683]
Zuzanna from the marketing team has a problem with AIConsole.
She gets such errors
![Screenshot 2024-01-24 at 15 31 27](https://github.com/10clouds/aiconsole/assets/152965457/ea6ed333-dd20-4abd-93fa-e50376e453b7)

### Steps to reproduce the error
1. Open the chat :D 

### Specifications
System: Mac
Version 0.2.10

**Comment by udislau** [comment]
This is not a bug 🙂. Zuza has no 'usage' field set for a material
