### ISSUE TITLE
User avatar pack

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#686]
Need to prepare an user avatar pack for AIConsole start

**Comment by kilodilo** [comment]
Here is the user avatar pack 
[User avatars.zip](https://github.com/10clouds/aiconsole/files/14066762/User.avatars.zip)
it is as univeral as possible :) uses pattern that corresponds with AIConsole logo
Here is Figma link https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=3768%3A22999&mode=design&t=OducVCURZgyemVqU-1

**Comment by cielecki** [comment]
While my initial preference for users would be to have blurry silhouettes like the one we had before - we can try to go with this one and see how it fits in the app itself.

**Comment by kilodilo** [comment]
It is more common to have more universal patterns as the initial avatar because a blurred silhouette is usually visibly a man or a woman and someone may not be happy having a different gender avatar :)
