### ISSUE TITLE
Chat's last_modified property issue

### ISSUE THREAD

**Issue by pwksn** [10clouds/aiconsole#693]
## Expected Behavior
The chat's `last_modified` property should be updated once the user interacts with the chat (e.g. sends a message).

## Actual Behavior
The chat's `last_modified` property is being updated once the user enters the chat, without any interaction.

## Preview

https://github.com/10clouds/aiconsole/assets/63242859/724397cd-06a1-4ebe-9e28-60c89cf6cab0

**Comment by udislau** [comment]
Fixed in https://github.com/10clouds/aiconsole/commit/c4d057f712def3df60e9cb1519d6847010f036b4
