### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#721]
I can see a problem within the version 
https://github.com/10clouds/aiconsole/releases/tag/v0.2.11-rc.4

1. user avatar doesn't load - looks like crashed - maybe its because we don't use any avatar package. We can implement this one form the task https://github.com/10clouds/aiconsole/issues/686
2. Loading spinner that @pwksn added doesn't show on my comp, looks like a crashed image

System:
Windows 11

**Comment by AGasior** [comment]
@kilodilo Can you share video with the issue?

**Comment by kilodilo** [comment]
@AGasior , here it is :)
You can see these two problems on the video:

https://github.com/10clouds/aiconsole/assets/152965457/6f8a27fd-3251-4978-a053-0920e0daccd6
