### ISSUE TITLE
Settings loading multiple notifications

### ISSUE THREAD

**Issue by kilodilo** [10clouds/aiconsole#722]
Here is the problem I see on the newest prereleased version:
![image](https://github.com/10clouds/aiconsole/assets/152965457/99ced4c7-714b-4c29-9a4a-cbf9c2a18097)
https://github.com/10clouds/aiconsole/releases/tag/v0.2.11-rc.4

the problem occurs when I start some conversation :) and it starts to pop up after a while

System:
Windows 11

**Comment by jakubbilko** [comment]
@kilodilo @udislau Tested the RC on my M1 Mac, not able to reproduce this (I waited a long time).

**Comment by kilodilo** [comment]
Maybe it is only like that on Windows, I don't know. :/

**Comment by aga-gasinska** [comment]
Checked on MacOS as well and didn't get it

**Comment by aga-gasinska** [comment]
Checked it on version [v0.2.11-rc.9]on Windows and it doesn't appear.
