### ISSUE TITLE
I accidentally pressed CTRL-W with AIConsole open with unsaved material, everything got lost (it should ask before closing)

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#737]

**Comment by aga-gasinska** [comment]
system confirmation modal must be added

**Comment by AGasior** [comment]
modal is visible 

<img width="1424" alt="Zrzut ekranu 2024-02-7 o 15 06 03" src="https://github.com/10clouds/aiconsole/assets/102804214/b1aad9dc-9b64-4087-9162-d8def25e7a57">
