### ISSUE TITLE
Remove horizontal scrolls 

### ISSUE THREAD

**Issue by aga-gasinska** [10clouds/aiconsole#738]
## Expected Behavior
There should be no horizontal scroll. 
## Actual Behavior
Horizontal scroll appears e.g. on the main page, settings page.

<img width="1440" alt="Zrzut ekranu 2024-02-5 o 10 33 54" src="https://github.com/10clouds/aiconsole/assets/155951278/09ae339a-a996-41f7-8a8e-5840958976ba">

## Specifications

- Version: [v0.2.11-rc.8](https://github.com/10clouds/aiconsole/releases/tag/v0.2.11-rc.8)
- Platform: MacOS resolution 2560 × 1600

**Comment by AGasior** [comment]
Horizontal scroll is not visible 

![Zrzut ekranu 2024-02-5 o 11 46 24](https://github.com/10clouds/aiconsole/assets/102804214/4f91bf34-521a-42fb-b5ee-ff75fa2b91e0)
