### ISSUE TITLE
Incorrect behavior when running code

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#752]
Current behaviour:

<img width="718" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/102ab578-4f57-4e47-a421-bab80c98e16e">

Expected:

<img width="739" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/ba2f9ba7-2ab0-4999-b5ab-9c19998ddcb2">

**Comment by cielecki** [comment]
To explain more, this is not about the error, it's about the fact that in our code execution env each line is executed seperatelly (and is printed to output), while in a python notebook it's executed until first error, and only last statement is printed

<img width="138" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/759b455c-1314-43aa-95de-02c37f37063b">

**Comment by udislau** [comment]
move to https://github.com/10clouds/aiconsole/issues/759
