### ISSUE TITLE
Domain checking does not work on windows

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#754]
Check asd.pl
Python:
is_domain_available('asd.pl')

Output:
Error checking domain asd.pl: [WinError 2] The system cannot find the file specified
False

**Comment by aga-gasinska** [comment]
Checked on Windows - the output is still the same as @cielecki has.  Error still occurs.

**Comment by aga-gasinska** [comment]
it works correctly in v0.2.11-rc.17
