### ISSUE TITLE
🐞 No padding

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#762]
<img width="174" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/d1807037-76aa-438b-9abe-546891171078">

**Comment by pwksn** [comment]
@cielecki can you check again and confirm if the problem is still there? I checked it on the `main` branch and I see no problem with the padding (both in browser and in Electron app):
![image](https://github.com/10clouds/aiconsole/assets/63242859/970ecfdc-6f81-4a12-8a99-39a1ee72f932)

**Comment by cielecki** [comment]
It's still there, on safari on web server version on Mac

**Comment by cielecki** [comment]
@pwksn It's still there, on safari on web server version on Mac

**Comment by pwksn** [comment]
@aga-gasinska I assigned you as a tester for this one, the issue was present in Safari browser only.

**Comment by AGasior** [comment]
Padding is added between "OpenAI API key" and input, but padding on inputs are too big.

<img width="1080" alt="Zrzut ekranu 2024-02-9 o 08 36 49" src="https://github.com/10clouds/aiconsole/assets/102804214/14c7c70d-051e-4bee-8a13-b6abc8a35259">

**Comment by AGasior** [comment]
Padding fixed

![Image](https://github.com/10clouds/aiconsole/assets/102804214/f9f701bd-6c88-4169-b300-b0be7fe74cf8)
