### ISSUE TITLE
🐞Stop no longer works 

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#767]
https://github.com/10clouds/aiconsole/assets/101296/2776b73c-b2e3-4799-b61d-2542bea6f5bd

**Comment by udislau** [comment]
@cielecki What how big was the chat? Did you multitask? Can't replicate the thing.

If you gonna spot it next time, go to the network and see the WS messages, filter by `is_error` and search thought the messages for `true`.

I think there is a possibility that front-end is sending StopChatClientMessage with incorrect chat_id value.

**Comment by aga-gasinska** [comment]
it's fine now
