### ISSUE TITLE
🐞 Chat getting replaced

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#779]
1. Open a chat - run some code there
2. Go to another chat start working
3. In some cases the 2nd chat content, which is on your screen will get replaced with the contents of the previous one (probably we are applying a websocket message to the wrong chat?)

**Comment by cielecki** [comment]
![Screenshot 2024-02-08 151321](https://github.com/10clouds/aiconsole/assets/101296/10950f4e-5af7-49cd-a6a5-309b27ec9e43)

**Comment by aga-gasinska** [comment]
checked and chats never got replaced
