### ISSUE TITLE
🐞 Chats content not loading on Windows

### ISSUE THREAD

**Issue by aga-gasinska** [10clouds/aiconsole#788]
## Describe the bug

Chats content is not loading. The spinner shows but they are not loading. I waited several minutes. 

## To Reproduce

1. Create 2 different chats in one project and make inputs. Wait until each chat provides outputs.
2. Create a new chat a make an input.
3. While the output is being produced go to the previous chat.

## Expected behavior

The content of previously created chats should load.

## Screenshots

https://github.com/10clouds/aiconsole/assets/155951278/b2e8bb4a-651a-43f4-8023-3e1722e39471

## Specifications

- OS: Windows
- Version [v0.2.11-rc.17]

**Comment by udislau** [comment]
Interesting🤔. I couldn't reproduce it.

@aga-gasinska, in all those chats, did you wait for the response, or did you close chats during message generation?

Can you please try to replicate the issue once again, preferably recording your actions?

**Comment by aga-gasinska** [comment]
@udislau rechecked and today it's fine however the problem with chats content not loading still appears but in a case when you leave a chat when the content is loading. I edited the description and added a new video showing the issue.

**Comment by aga-gasinska** [comment]
I also want to add that when you go to Agents or Materials they don't load as well - black screen appears.

**Comment by aga-gasinska** [comment]
it's about image generation

**Comment by aga-gasinska** [comment]
checked on v0.2.11-rc.20 with the same prompt and everything works fine
