### ISSUE TITLE
🐞 After I click around the app I eventually get two scrollbars (Mac)

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#794]
https://github.com/10clouds/aiconsole/assets/101296/a5bf2ff5-fcef-438f-aa50-78f7b0433008

**Comment by pwksn** [comment]
I observed similar behaviour in agent's details when "This agent is overwriting a default system agent" is present.
![image](https://github.com/10clouds/aiconsole/assets/63242859/cba105bb-1c55-4e79-b165-d4937c0f1040)

cc @cielecki @AGasior

**Comment by AGasior** [comment]
I fixed also agents page

**Comment by aga-gasinska** [comment]
checked on v0.2.11-rc.20 on chats and agents and didn't get a double scrollbar
