### ISSUE TITLE
After creating Note with repetitive words the chat stopped working

### ISSUE THREAD

**Issue by ZiewiecK** [10clouds/aiconsole#810]
1. Go to AIConsole app.
2. Click "Add new" button.
3. Pick the "Note" type.
4. In "Usage" and in "Text" fields write some word, e.g. "test" many times (in my case it was around 1000)
5. Save it.
6. Go to chat.
7. Add any question.

## Current behavior

Chat stopped working. User is getting empty answers. After clicking on answer user is getting error message (screenshots attached). User is getting error message in console  **Error code: 400 - {'error': {'message': "Sorry! We've encountered an issue with repetitive patterns in your prompt. Please try again with a different prompt.", 'type': 'invalid_request_error', 'param': 'prompt', 'code': None}}**

## Expected behavior

Chat is working with no issue

## Screenshots

<img width="810" alt="Screenshot 2024-02-15 at 11 47 50" src="https://github.com/10clouds/aiconsole/assets/52559604/06976f10-8e9e-43ca-bf8b-accdb88ccb05">
<img width="1134" alt="Screenshot 2024-02-15 at 11 47 59" src="https://github.com/10clouds/aiconsole/assets/52559604/4fd8f631-5dd6-4f82-9496-1c176a27a6ad">

## Specifications

- OS: MacOS Sonoma 14
- Version [v0.2.12-rc.1]

**Comment by udislau** [comment]
Show err to the user

**Comment by udislau** [comment]
Can't replicate
