### ISSUE TITLE
Adjust the error message format in Settings -> Email address to the general design for error messages

### ISSUE THREAD

**Issue by ZiewiecK** [10clouds/aiconsole#812]
## Is your feature request related to a problem?

When user is in their Settings and they are trying to add incorrect email address -> they are getting error message, but this error message does not look like other ones in the app

## Describe the solution you'd like

Please adjust this error message to the design rules in the app

## Current result:
<img width="911" alt="errorMessage" src="https://github.com/10clouds/aiconsole/assets/52559604/4fbeba37-63bc-4010-b207-25a88e8ceb2f">

**Comment by cielecki** [comment]
Remove the email field

**Comment by udislau** [comment]
Email field was removed in 7c5f88c7f28b2a6620d93702e0b59749310aa38c

Need to adjust frontend
