### ISSUE TITLE
When user writes a random characters in the chat there is no reaction from the agent

### ISSUE THREAD

**Issue by ZiewiecK** [10clouds/aiconsole#817]
## To Reproduce

1. Go to the AIConsole app.
2. Create new chat or use existing one.
3. Write some characters (that do not make a sense).
4. Wait.

## Current behavior
 User sees the analysis and the next step should be asking question to the user if they can sepcify or give more details.

## Expected behavior

There is a question to the user if they can specify their request/question.

## Screenshots

<img width="1296" alt="Screenshot 2024-02-15 at 15 00 03" src="https://github.com/10clouds/aiconsole/assets/52559604/d2e4df2b-e931-4106-a3c2-bb0ed8e8a40a">
<img width="1296" alt="Screenshot 2024-02-15 at 15 00 16" src="https://github.com/10clouds/aiconsole/assets/52559604/57b6433a-9627-44a1-a75f-515b6c8027e8">

## Specifications

- OS: MacOS Sonoma 14
- Version [e.g. 0.2.12]

**Comment by udislau** [comment]
https://github.com/10clouds/aiconsole/commit/d2052f0e11b6f111272e5d0c55a11861500b5dc3
