### ISSUE TITLE
Old custom agents stopped working🐞 

### ISSUE THREAD

**Issue by DVLevin** [10clouds/aiconsole#818]
## Describe the bug

Old custom agents stopped working.

## To Reproduce

1. Create a chat in the existing AIC , where old custom agents (from 2.10) are
2. Talk to them directly 
3. You will have the "director" window, but not the output 

## Screenshots

<img width="1199" alt="Screenshot 2024-02-16 at 09 35 02" src="https://github.com/10clouds/aiconsole/assets/118979778/a7cef949-818d-4ccb-a371-e9e2298a056b">

## Specifications

- OS: MacOS Ventura 13.5.1
- Version [ 2.12 ] (same was at 2.11)

**Comment by udislau** [comment]
https://github.com/10clouds/aiconsole/commit/116ca88051d296bbd118dfbce4707b00052e9c3e

**Comment by cielecki** [comment]
# Port 2.9 agent to 2.11
        if execution_mode == "aiconsole.core.execution_modes.normal:execution_mode_normal":
            execution_mode = "aiconsole.core.chat.execution_modes.normal:execution_mode"
        elif execution_mode == "aiconsole.core.execution_modes.interpreter:execution_mode_interpreter":
            execution_mode = "aiconsole.core.chat.execution_modes.interpreter:execution_mode"
        elif execution_mode == "aiconsole.core.execution_modes.example_countdown:execution_mode_example_countdown":
            execution_mode = "aiconsole.core.chat.execution_modes.example_countdown:execution_mode"

This should be done in agent loading not import and validate, for example for the purposes of properly editing this stuff

**Comment by udislau** [comment]
04d8bf8fb6c63da8e09ba6eead6a569ac1e2b1d3
