### ISSUE TITLE
🐞 Reload of chat history after delete (visible with many chats)

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#820]
https://github.com/10clouds/aiconsole/assets/101296/5a93f6f8-7075-453c-8211-5e8caccc0497

**Comment by ZiewiecK** [comment]
https://github.com/10clouds/aiconsole/assets/52559604/e8ed0f46-9cbc-4d05-b8bc-53dc409598fd

Retested on macOS Sonoma 14 (Windows is not working currently for the version[v0.2.13-rc.1])
Reload of chat history is not happening
