### ISSUE TITLE
Problems with Packages by AUtomator🐞 

### ISSUE THREAD

**Issue by DVLevin** [10clouds/aiconsole#851]
## Describe the bug

I have a constant problems with packages when trying to do simple things with the AIC. 

like: I want to extract images from doc, but lxml is not working (while AIC installed and re-installed it). Same stuff with pandas etc. 

Take a look at screenshot attached. 

<img width="852" alt="Screenshot 2024-02-20 at 14 05 12" src="https://github.com/10clouds/aiconsole/assets/118979778/9cc69f9c-353d-4554-8c0d-27eb01282872">

v0.2.12

**Comment by cielecki** [comment]
@DVLevin What operating system?
