### ISSUE TITLE
Version v0.2.13-rc.1  is not working on Windows 11 

### ISSUE THREAD

**Issue by ZiewiecK** [10clouds/aiconsole#866]
## To Reproduce

1. Install the version v0.2.13-rc.1 in Windows.
2. Open the app.
3. Try using existing or new chat.

## Current behavior

App stops working.

## Screenshots

https://drive.google.com/file/d/1xiFzT5IJex180Ce9gRPkRkEtxCe6Yqee/view?usp=sharing

## Specifications

- OS: Windows 11
- Version v0.2.13-rc.1

**Comment by dominikborkowski-10clouds** [comment]
I also described the same issue in [#240](https://github.com/10clouds/aiconsole/issues/240)
