### ISSUE TITLE
🐞 This should be resolved at toml loading level

### ISSUE THREAD

**Issue by cielecki** [10clouds/aiconsole#873]
<img width="546" alt="image" src="https://github.com/10clouds/aiconsole/assets/101296/2f355f5e-b3ea-46e4-ac09-66ecdb83dc66">

**Comment by cielecki** [comment]
I removed this for now, this needs to be readded in toml loading

**Comment by udislau** [comment]
04d8bf8fb6c63da8e09ba6eead6a569ac1e2b1d3
