### ISSUE TITLE
🚀 With No internet show "No internet connection"

### ISSUE THREAD

**Issue by udislau** [10clouds/aiconsole#891]
## Is your feature request related to a problem?

Opening app without Internet access shows "Provide API key screen"

**Comment by kilodilo** [comment]
I suppose it should shows this screen instead of Add API key screen.
https://www.figma.com/file/6YjcNnpuDJ3ZDhMQNtSptr/AI-Console?type=design&node-id=4918%3A25516&mode=design&t=uo7tPgsslh8za6vG-1

![Uploading Console connection.png…]()
