### ISSUE TITLE
🐞 Clicking send message 2 times super fast results in blocked chat

### ISSUE THREAD

**Issue by udislau** [10clouds/aiconsole#897]
## To Reproduce

1. Open chat
2. Enter prompt
3. Click 2 times fast 

## Expected behavior

Only 1 message needs to be sent and processing needs to be stoped. 

## Screenshots

https://github.com/10clouds/aiconsole/assets/30052145/2b24ddda-a2e5-463e-8872-a1af3006666e

## Specifications

- OS: MacOS
- Version 33bfa6721ba38417f48e55c769f87d865136c2ef

**Comment by nkvch** [comment]
[solved](https://github.com/10clouds/aiconsole/commit/c88e8d070f45a3d437e3ef20b2b5b241808ef347)
