### ISSUE TITLE
While writing prompts, the cursor jumps to end of text 🐞 

### ISSUE THREAD

**Issue by Chris10C** [10clouds/aiconsole#903]
As in title - while trying to edit the prompt, letters are written not in where you set the cursor but automatically at the end of the last verse. See video.

## Specifications

- OS: Windows 10
- Version  0.2.13

[](url)

**Comment by Chris10C** [comment]
https://github.com/10clouds/aiconsole/assets/136096370/7f02d619-5a16-4df9-a444-fe32f1065377

**Comment by udislau** [comment]
Already fixed, gonna be available in the next release (next Wed)
