### ISSUE TITLE
🐞 Cannot enable agent that is disabled by default

### ISSUE THREAD

**Issue by nkvch** [10clouds/aiconsole#907]
## Describe the bug

Cannot enable agent that is disabled by default. Changing the toggle to "Enabled" ends up in no changes after couple of seconds. When I click on "Enabled" I see a request sent to /status-change ep with legit params and "ok" response. But after a couple of seconds data comes from /assets with that agent still having `{ enabled: false }`

## To Reproduce

1.  Click on 3 dots on one of disabled agents on the left sidebar
2. Choose "Enabled"
3. Try to talk to this agent in some chat (will not be avaiable)

## Expected behavior

Agents should be able to disable and enable.

## Screenshots

https://github.com/10clouds/aiconsole/assets/58534398/5558a2e0-b8e4-4204-9edd-1b5f378b220e

## Specifications

- OS: [Windows]
- Version [0.2.13]

**Comment by udislau** [comment]
Fixed
