### ISSUE TITLE
🐞 No clear flow of how new chat becomes existing chat

### ISSUE THREAD

**Issue by nkvch** [10clouds/aiconsole#910]
## Describe the bug

I create click "New chat" and start chatting. New chat does not appear on the sidebar, even after reloading of the page - only restart of the server helps. "New chat" remains "new" (the url) even after conversation has began - so clicking on "New chat" once again does not open empty new chat - it remains on the same chat, which is not "new" anymore (shown in the beginning of the video).

## To Reproduce

1. Start new chat and ask something.
2. then click "New chat" once again (no new chat will start)
3. Leave the chat by clicking on any other existing chat on the sidebar (you will not be able to return to newly started chat - as it will not appear on the sidebar until server restart)

## Expected behavior

I guess after the communication is started the url of the chat should change to the freshly created chat id and new chat should appear in the sidebar - like it happens in ChatGPT

## Screenshots

[screen-capture (2).webm](https://github.com/10clouds/aiconsole/assets/58534398/2ccee515-3e56-4cc3-9b58-9dbf627b48ba)

## Specifications

- OS: [Windows]
- Version [0.2.13]

**Comment by udislau** [comment]
@nkvch After receiving Server message form WS, change path to chat id

**Comment by udislau** [comment]
done with different approach in https://github.com/10clouds/aiconsole/commit/95fed4b49db70fc6251a844cfc4ce6b97a5ed2ea
