### ISSUE TITLE
🐞 Countdown code execution icon

### ISSUE THREAD

**Issue by nkvch** [10clouds/aiconsole#914]
## Describe the bug

in Countdown while "print(something)" is exectuing the frontend shows error icon.

## To Reproduce

1. open new chat
2. ask to countdown

## Expected behavior

should show "processing" icon

## Screenshots

[screen-capture (3).webm](https://github.com/10clouds/aiconsole/assets/58534398/80ceb877-c448-481e-b93c-5ed6d286efc2)

## Specifications

- OS: [Windows]
- Version [e.g. 0.2.13]

**Comment by udislau** [comment]
fixed
